import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simplified translations - for full version, load from GitHub
const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Header
    'header.home': 'Главная',
    'header.about': 'О проекте',
    'header.invest': 'Инвестировать',
    'header.dashboard': 'Дэшборд',
    'header.roadmap': 'Roadmap',
    'header.profile': 'Профиль',
    'header.connectWallet': 'Подключить кошелек',
    'header.disconnect': 'Отключить',
    
    // Hero
    'hero.title': 'Инвестируйте в рентал-бизнес Toyota в Паттайе',
    'hero.mainTitle': 'Инвестируйте',
    'hero.mainTitleLine2': 'в рентал-бизнес',
    'hero.subtitle': 'Пассивный доход от аренды автомобилей в Таиланде с криптоинвестициями',
    'hero.carsInfo': 'автомобилей Toyota • От $1,000 • 1.7%/мес',
    'hero.orOwnership': 'или авто в собственность',
    'hero.invested': 'Инвестировано',
    'hero.investors': 'Инвесторов',
    'hero.cars': 'Автомобилей',
    'hero.investNow': 'Инвестировать сейчас',
    'hero.collected': 'Собрано из',
    'hero.monthlyReturn': '/мес.',
    'hero.income': 'доход',
    'hero.forecast': 'Прогноз',
    
    // Investment Tiers
    'tiers.title': 'Инвестиционные тиры',
    'tiers.options': 'Варианты участия',
    'tiers.subtitle': 'Выберите подходящий вариант инвестирования',
    'tiers.from': 'от',
    'tiers.selectTier': 'Выбрать тир',
    'tiers.connectWallet': 'Подключите кошелек',
    'tiers.staking': 'Стейкинг',
    'tiers.stakingBadge': 'до 1.7%/мес',
    'tiers.stakingDesc': 'Пассивный доход с гибкими условиями вывода',
    'tiers.carsLeft': 'авто осталось',
    'tiers.minInvestment': 'Минимальная инвестиция',
    'tiers.stakingFeature1': '1.7% в месяц (20.4% годовых)',
    'tiers.stakingFeature2': 'Вывод в любой момент',
    'tiers.stakingFeature3': '5% комиссия при выводе до 6 мес',
    'tiers.stakingFeature4': 'Ежемесячное начисление процентов',
    'tiers.carShare': 'Доля в автомобиле',
    'tiers.carShareDesc': 'Получите автомобиль в собственность или гарантированный возврат',
    'tiers.carShareFeature1': 'Через 6 мес: +20% возврат ИЛИ ждать авто',
    'tiers.carShareFeature2': 'Автомобиль в собственность после выплаты кредита',
    'tiers.carShareFeature3': 'Приоритет: кто первый - тот получает авто',
    'tiers.carShareFeature4': 'Можно изменить выбор до закрытия кредита',
    'tiers.invest': 'Инвестировать',
    'tiers.currencies': 'Принимаемые валюты:',
    'tiers.networkFee': 'Комиссия сети:',
    'tiers.deposit': 'Зачисление:',
    'tiers.directToWallet': 'напрямую на корпоративный кошелек',
    
    // About
    'about.title': 'О проекте',
    'about.subtitle': 'Thailand My Car — это инновационная платформа для инвестиций в рентал-бизнес автомобилей Toyota в Паттайе',
    'about.description': 'Действующий бизнес по прокату автомобилей в Паттайе с проверенными показателями доходности',
    'about.cars': 'Автопарк',
    'about.carsSubtitle': 'автомобилей в управлении',
    'about.newToyotaCars': 'Новых автомобилей Toyota',
    'about.stableMonthlyFlow': 'стабильный поток за месяц',
    'about.fleetOccupancy': 'Загрузка автопарка 2025',
    'about.touristCenter': 'Туристический центр',
    'about.monthlyIncome': 'Доход',
    'about.monthlyIncomeSubtitle': 'стабильный поток в месяц',
    'about.occupancy': 'Загрузка',
    'about.occupancySubtitle': 'средний показатель аренды',
    'about.location': 'Локация',
    'about.locationValue': 'Паттайя',
    'about.locationSubtitle': 'туристический центр Таиланда',
    'about.growthTitle': 'История роста',
    'about.growthHistory': 'История роста компании',
    'about.carsUnit': 'АВТО',
    'about.cars3': '3 авто',
    'about.cars6': '6 авто',
    'about.cars8': '8 авто',
    'about.launch': 'Запуск проекта',
    'about.start': 'Старт',
    'about.growth': 'Рост',
    'about.now': 'Сейчас',
    'about.insurance': 'Страхование',
    'about.insuranceDesc': 'Все автомобили застрахованы по первому классу для максимальной защиты инвесторов.',
    'about.insuranceFullDesc': 'Полная страховка Type 1 (ชั้น 1) на авто и пассажиров',
    'about.insurancePoint1': 'Полное покрытие ущерба автомобиля',
    'about.insurancePoint2': 'Угон и злоумышленные действия',
    'about.insurancePoint3': 'Стихийные бедствия (наводнение, пожар)',
    'about.insurancePoint4': 'Медицинские расходы водителя и пассажиров',
    'about.insurancePoint5': 'Ответственность перед третьими лицами',
    'about.insurancePoint6': 'Эвакуация и помощь на дороге 24/7',
    'about.transparency': 'Прозрачность',
    'about.transparencyDesc': 'Полная отчетность по аренде и выплатам через личный кабинет и смарт-контракты.',
    'about.transparencyFullDesc': 'Ежемесячные отчеты и доступ к метрикам в реальном времени',
    'about.experience': 'Опыт',
    'about.experienceDesc': 'Более 5 лет на рынке аренды автомобилей в Таиланде гарантируют эффективность управления.',
    'about.experienceFullDesc': '2+ года успешной работы на рынке рентала в Таиланде',
    'about.fleetTitle': 'Наш автопарк Toyota',
    'about.fleetDesc': 'Мы используем только надежные и популярные модели Toyota, обеспечивающие высокую ликвидность.',
    'about.velozName': 'Toyota Veloz',
    'about.velozDesc': 'Премиальный 7-местный кроссовер',
    'about.yarisName': 'Toyota Yaris',
    'about.yarisDesc': 'Компактный седан для города',
    
    // Footer
    'footer.description': 'Инвестируйте в рентал-бизнес автомобилей в Таиланде',
    'footer.contacts': 'Контакты',
    'footer.rights': 'Все права защищены',
    'footer.disclaimer': 'Инвестиции сопряжены с рисками. Проконсультируйтесь со специалистом.',
    
    // Cookies
    'cookies.message': 'Мы используем cookies для улучшения вашего опыта на сайте.',
    'cookies.accept': 'Принять',
    'cookies.decline': 'Отклонить',
    
    // Profile
    'profile.back': 'Назад',
    'profile.yourProfile': 'Ваш профиль',
    'profile.memberSince': 'Участник с',
    'profile.totalInvested': 'Всего инвестировано',
    'profile.investments': 'Инвестиций',
    'profile.activeInvestments': 'Активные',
    'profile.inBaht': 'В батах',
    'profile.personalInfo': 'Личная информация',
    'profile.name': 'Имя',
    'profile.namePlaceholder': 'Ваше имя',
    'profile.bio': 'О себе',
    'profile.bioPlaceholder': 'Расскажите немного о себе...',
    'profile.saveProfile': 'Сохранить профиль',
    'profile.saving': 'Сохранение...',
    'profile.updateSuccess': 'Профиль успешно обновлен',
    'profile.loadError': 'Не удалось загрузить профиль',
    'profile.saveError': 'Не удалось сохранить профиль',
    'profile.connectWallet': 'Подключите кошелек',
    'profile.connectWalletDesc': 'Для просмотра профиля необходимо подключить кошелек',

    // Roadmap
    'roadmap.title': 'План развития проекта',
    'roadmap.subtitle': 'Наш путь к успеху',
    'roadmap.q4_2025': 'Q4 2025',
    'roadmap.launch': 'Запуск платформы',
    'roadmap.launchItems': 'Запуск платформы|Начало сбора инвестиций|Покупка первых автомобилей',
    'roadmap.dec_jan': 'Декабрь 2025 - Январь 2026',
    'roadmap.fundraising': 'Сбор средств',
    'roadmap.fundraisingItems': 'Достижение ฿2.8M|Полное заполнение 6-7 слотов|Активация всех автомобилей',
    'roadmap.jan_2026': 'Январь 2026',
    'roadmap.roundClose': 'Закрытие раунда',
    'roadmap.roundCloseItems': 'Закрытие сбора|Регистрация компании|Начало операций',
    'roadmap.feb_2026': 'Февраль 2026',
    'roadmap.legal': 'Юридическое оформление',
    'roadmap.legalItems': 'Регистрация юр. лица|Оформление автомобилей|Лицензии и разрешения',
    'roadmap.mar_2026': 'Март 2026',
    'roadmap.firstPayouts': 'Первые выплаты',
    'roadmap.firstPayoutsItems': 'Запуск аренды|Первые выплаты инвесторам|Стабилизация операций',
    'roadmap.jul_2026': 'Июль 2026',
    'roadmap.expansion': 'Расширение',
    'roadmap.expansionItems': 'Выкуп 6-месячных инвестиций|Расширение автопарка|Новые локации',
    'roadmap.oct_2026': 'Октябрь 2026',
    'roadmap.newProducts': 'Новые продукты',
    'roadmap.newProductsItems': 'Запуск новых услуг|Партнерство с отелями|Развитие бренда',
    'roadmap.2027': '2027',
    'roadmap.continued': 'Продолжение роста',
    'roadmap.continuedItems': 'Масштабирование бизнеса|Новые инвестиционные раунды|Международное расширение',
    // Dashboard
    'dashboard.myDashboard': 'Личный кабинет',
    'dashboard.manageInvestments': 'Управление вашими активами и отслеживание прибыли',
    'dashboard.invested': 'Инвестировано',
    'dashboard.earned': 'Начислено',
    'dashboard.totalBalance': 'Общий баланс',
    'dashboard.active': 'Активных тиров',
    'dashboard.earningsProjection': 'Прогноз доходности',
    'dashboard.balanceByMonth': 'Рост вашего капитала во времени',
    'dashboard.balance': 'Баланс',
    'dashboard.monthlyIncome': 'Доход в месяц',
    'dashboard.accumulated': 'Накоплено',
    'dashboard.withdraw': 'Вывести',
    'dashboard.staking': 'Стейкинг',
    'dashboard.carShare': 'Доля в авто',
    'dashboard.connectWallet': 'Подключите кошелек',
    'dashboard.connectToView': 'Чтобы увидеть свои инвестиции, необходимо авторизоваться через MetaMask',
    'dashboard.loading': 'Загрузка данных...', 
    'dashboard.noInvestments': 'Инвестиций не найдено',
    'dashboard.startInvestingHere': 'Ваши будущие инвестиции появятся здесь после оплаты',
    'dashboard.withdrawn': 'Выведено',
    'dashboard.withdrawalTypeLabel': 'Тип вывода:',
    'dashboard.withdrawAll': 'Все средства',
    'dashboard.withdrawAllDesc': 'Тело вклада + накопленные проценты',
    'dashboard.withdrawEarnings': 'Только проценты',
    'dashboard.withdrawEarningsDesc': 'Накопленный доход, тело остается',
    'dashboard.withdrawPrincipal': 'Только тело вклада',
    'dashboard.withdrawPrincipalDesc': 'Основная сумма инвестиции',
    'dashboard.baseAmount': 'Сумма:',
    'dashboard.baseFee': 'Базовая комиссия (3%):',
    'dashboard.earlyFeeMayApply': '+ комиссия за ранний вывод (5%) если не истек срок',
    'dashboard.estimatedAmount': 'Примерная сумма к получению:',
    'dashboard.withdrawalWallet': 'Кошелек для вывода (опционально)',
    'dashboard.withdrawalWalletHint': 'Если не указан, будет использован подключенный кошелек',
    'dashboard.submitWithdrawal': 'Отправить запрос',
    'dashboard.processing': 'Обработка...',
    'dashboard.withdrawalSuccess': 'Запрос отправлен!',
    'dashboard.withdrawalSuccessDesc': 'Ваш запрос на вывод средств будет обработан администратором в течение 48 часов.',
    'dashboard.withdrawalPending': 'Ожидает одобрения...',
    'dashboard.walletRequired': 'Пожалуйста, подключите кошелек или введите адрес для вывода',
    'dashboard.invalidWalletFormat': 'Неверный формат адреса кошелька',
    'dashboard.withdrawalError': 'Ошибка при отправке запроса на вывод',

    // Alert
    'alert.connectWallet': 'Пожалуйста, подключите кошелек для инвестирования',

    // Chat
    'chat.agentName': 'Консультант TMC',
    'chat.consultantOnline': 'Онлайн',
    'chat.typing': 'Печатает...',
    'chat.end': 'Завершить',
    'chat.endChat': 'Завершить чат',
    'chat.endChatConfirm': 'Вы уверены, что хотите завершить чат?',
    'chat.contactManager': 'Связаться с менеджером',
    'chat.waitingForManager': 'Ожидание менеджера...',
    'chat.startChat': 'Начать чат',
    'chat.introduceYourself': 'Представьтесь, пожалуйста',
    'chat.yourName': 'Ваше имя',
    'chat.namePlaceholder': 'Введите имя',
    'chat.emailOptional': 'Email (необязательно)',
    'chat.welcomeMessage': 'Здравствуйте, {name}! Чем могу помочь?',
    'chat.managerRequestSent': 'Запрос менеджеру отправлен. Ожидайте ответа.',

    // Header extras
    'header.subtitle': 'Инвестиции в рентал',
    'header.signing': 'Подпись...',
    'header.login': 'Войти',
    'header.lightTheme': 'Светлая',
    'header.darkTheme': 'Тёмная',
    'header.authError': 'Не удалось авторизовать кошелек. Попробуйте ещё раз.',
    'header.logging': 'Вход...',

    // Contact
    'contact.title': 'Связаться с нами',
    'contact.description': 'Свяжитесь с нашей командой для поддержки, партнёрства или общих вопросов',
    'contact.messageSent': 'Сообщение отправлено!',
    'contact.thankYou': 'Спасибо за обращение. Мы ответим в течение 24 часов.',
    'contact.yourName': 'Ваше имя',
    'contact.emailAddress': 'Email адрес',
    'contact.subject': 'Тема',
    'contact.selectSubject': 'Выберите тему',
    'contact.generalInquiry': 'Общий вопрос',
    'contact.technicalSupport': 'Техническая поддержка',
    'contact.partnership': 'Партнёрство',
    'contact.securityIssue': 'Вопрос безопасности',
    'contact.other': 'Другое',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите, чем мы можем помочь...',
    'contact.sendMessage': 'Отправить сообщение',
    'contact.quickContact': 'Быстрая связь',
    'contact.email': 'Email',
    'contact.joinCommunity': 'Присоединиться',
    'contact.followUs': 'Мы в соцсетях',
    'contact.supportHours': 'Часы работы',
    'contact.mondayFriday': 'Понедельник - Пятница',
    'contact.remoteFirst': 'Удалённая команда',
    'contact.globalTeam': 'Глобальная команда',

    // Modal
    'modal.agreementTitle': 'ИНВЕСТИЦИОННОЕ СОГЛАШЕНИЕ (ОФЕРТА)',
    'modal.agreementIntro': 'Пожалуйста, внимательно ознакомьтесь с условиями участия в проекте Thailand My Car перед внесением средств.',
    'modal.agreementNature': 'Характер сделки:',
    'modal.agreementNatureText': 'Вы вносите средства для совместного приобретения и эксплуатации автомобилей. Это не является банковским вкладом.',
    'modal.agreementNotPublic': 'Частное предложение',
    'modal.agreementRisks': 'Риски:',
    'modal.agreementRisksText': 'Инвестиции в аренду авто связаны с рыночными рисками, износом техники и форс-мажорами.',
    'modal.agreementNotGuaranteed': 'Доход не гарантирован на 100%',
    'modal.agreementRisksNote': ' Однако все авто застрахованы.',
    'modal.agreementReturn': 'Возврат средств:',
    'modal.agreementReturnText': 'Условия возврата зависят от выбранного тира (6 месяцев или владение).',
    'modal.agreementTaxes': 'Налоги:',
    'modal.agreementTaxesText': 'Инвестор самостоятельно несет ответственность за уплату налогов в своей юрисдикции.',
    'modal.agreementDisputes': 'Споры:',
    'modal.agreementDisputesText': 'Все споры решаются путем переговоров или согласно законодательству Таиланда.',
    'modal.agreementAge': 'Возраст:',
    'modal.agreementAgeText': 'Вам должно быть не менее',
    'modal.agreementAgeYears': '18 лет',
    'modal.agreementData': 'Данные:',
    'modal.agreementDataText': 'Вы соглашаетесь на обработку минимально необходимых данных для учета инвестиции.',
    'modal.agreementRoadmap': 'Roadmap:',
    'modal.agreementRoadmapText': 'Сроки в дорожной карте являются ориентировочными.',
    'modal.agreementVersion': 'Версия 1.0.4 • 2025',
    'modal.scrollDown': 'Прокрутите вниз, чтобы прочитать',
    'modal.agreeTerms': 'Я согласен с условиями и осознаю риски',
    'modal.scrollToEnd': 'Прочтите соглашение до конца',
    'modal.continue': 'Продолжить',
    'modal.readAgreement': 'Прочтите соглашение',
    'modal.amount': 'Сумма инвестиции',
    'modal.expectedReturn': 'Ожидаемый доход (6 мес)',
    'modal.expectedReturnCar': 'Ожидаемый бонус или авто',
    'modal.next': 'Далее',
    'modal.payViaWallet': 'Оплатить через кошелек',
    'modal.confirmInWallet': 'Подтвердите в MetaMask',
    'modal.applicationCreated': 'Заявка создана!',
    'modal.done': 'Готово',
    'modal.back': 'Назад',
  },
  en: {
    // Header
    'header.home': 'Home',
    'header.about': 'About',
    'header.invest': 'Invest',
    'header.dashboard': 'Dashboard',
    'header.roadmap': 'Roadmap',
    'header.profile': 'Profile',
    'header.connectWallet': 'Connect Wallet',
    'header.disconnect': 'Disconnect',
    
    // Hero
    'hero.title': 'Invest in Toyota Rental Business in Pattaya',
    'hero.mainTitle': 'Invest',
    'hero.mainTitleLine2': 'in rental business',
    'hero.subtitle': 'Passive income from car rental in Thailand with crypto investments',
    'hero.carsInfo': 'Toyota vehicles • From $1,000 • 1.7%/mo',
    'hero.orOwnership': 'or car ownership',
    'hero.invested': 'Invested',
    'hero.investors': 'Investors',
    'hero.cars': 'Cars',
    'hero.investNow': 'Invest Now',
    'hero.collected': 'Collected from',
    'hero.monthlyReturn': '/mo.',
    'hero.income': 'income',
    'hero.forecast': 'Forecast',
    
    // Investment Tiers
    'tiers.title': 'Investment Tiers',
    'tiers.options': 'Participation Options',
    'tiers.subtitle': 'Choose your investment option',
    'tiers.from': 'from',
    'tiers.selectTier': 'Select Tier',
    'tiers.connectWallet': 'Connect Wallet',
    'tiers.staking': 'Staking',
    'tiers.stakingBadge': 'up to 1.7%/mo',
    'tiers.stakingDesc': 'Passive income with flexible withdrawal terms',
    'tiers.carsLeft': 'cars left',
    'tiers.minInvestment': 'Minimum investment',
    'tiers.stakingFeature1': '1.7% per month (20.4% annually)',
    'tiers.stakingFeature2': 'Withdraw anytime',
    'tiers.stakingFeature3': '5% fee for withdrawal before 6 months',
    'tiers.stakingFeature4': 'Monthly interest accrual',
    'tiers.carShare': 'Car Share',
    'tiers.carShareDesc': 'Get a car ownership or guaranteed return',
    'tiers.carShareFeature1': 'After 6 months: +20% return OR wait for car',
    'tiers.carShareFeature2': 'Car ownership after loan repayment',
    'tiers.carShareFeature3': 'Priority: first come - first served',
    'tiers.carShareFeature4': 'Can change choice before loan closes',
    'tiers.invest': 'Invest',
    'tiers.currencies': 'Accepted currencies:',
    'tiers.networkFee': 'Network fee:',
    'tiers.deposit': 'Deposit:',
    'tiers.directToWallet': 'direct to corporate wallet',
    
    // About
    'about.title': 'About Project',
    'about.subtitle': 'Thailand My Car is an innovative platform for investments in Toyota car rental business in Pattaya',
    'about.description': 'Operating car rental business in Pattaya with proven profitability',
    'about.cars': 'Fleet',
    'about.carsSubtitle': 'cars under management',
    'about.newToyotaCars': 'New Toyota vehicles',
    'about.stableMonthlyFlow': 'stable monthly flow',
    'about.fleetOccupancy': 'Fleet occupancy 2025',
    'about.touristCenter': 'Tourist center',
    'about.monthlyIncome': 'Income',
    'about.monthlyIncomeSubtitle': 'stable monthly flow',
    'about.occupancy': 'Occupancy',
    'about.occupancySubtitle': 'average rental rate',
    'about.location': 'Location',
    'about.locationValue': 'Pattaya',
    'about.locationSubtitle': 'Thailand tourism hub',
    'about.growthTitle': 'Growth History',
    'about.growthHistory': 'Company growth history',
    'about.carsUnit': 'CARS',
    'about.cars3': '3 cars',
    'about.cars6': '6 cars',
    'about.cars8': '8 cars',
    'about.launch': 'Project Launch',
    'about.start': 'Start',
    'about.growth': 'Growth',
    'about.now': 'Now',
    'about.insurance': 'Insurance',
    'about.insuranceDesc': 'All cars are covered by first-class insurance for maximum investor protection.',
    'about.insuranceFullDesc': 'Full Type 1 (ชั้น 1) insurance for vehicles and passengers',
    'about.insurancePoint1': 'Full vehicle damage coverage',
    'about.insurancePoint2': 'Theft and malicious damage',
    'about.insurancePoint3': 'Natural disasters (flood, fire)',
    'about.insurancePoint4': 'Medical expenses for driver and passengers',
    'about.insurancePoint5': 'Third party liability',
    'about.insurancePoint6': 'Roadside assistance 24/7',
    'about.transparency': 'Transparency',
    'about.transparencyDesc': 'Full reporting on rentals and payouts via dashboard and smart contracts.',
    'about.transparencyFullDesc': 'Monthly reports and real-time access to metrics',
    'about.experience': 'Experience',
    'about.experienceDesc': 'Over 5 years in Thailand car rental market guarantee management efficiency.',
    'about.experienceFullDesc': '2+ years of successful operation in Thailand rental market',
    'about.fleetTitle': 'Our Toyota Fleet',
    'about.fleetDesc': 'We use only reliable and popular Toyota models ensuring high liquidity.',
    'about.velozName': 'Toyota Veloz',
    'about.velozDesc': 'Premium 7-seater crossover',
    'about.yarisName': 'Toyota Yaris',
    'about.yarisDesc': 'Compact city sedan',
    
    // Footer
    'footer.description': 'Invest in car rental business in Thailand',
    'footer.contacts': 'Contacts',
    'footer.rights': 'All rights reserved',
    'footer.disclaimer': 'Investments carry risks. Consult with a specialist.',
    
    // Cookies
    'cookies.message': 'We use cookies to improve your experience on our site.',
    'cookies.accept': 'Accept',
    'cookies.decline': 'Decline',
    
    // Profile
    'profile.back': 'Back',
    'profile.yourProfile': 'Your Profile',
    'profile.memberSince': 'Member since',
    'profile.totalInvested': 'Total Invested',
    'profile.investments': 'Investments',
    'profile.activeInvestments': 'Active',
    'profile.inBaht': 'In Baht',
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Name',
    'profile.namePlaceholder': 'Your name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.saveProfile': 'Save Profile',
    'profile.saving': 'Saving...',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.loadError': 'Failed to load profile',
    'profile.saveError': 'Failed to save profile',
    'profile.connectWallet': 'Connect Wallet',
    'profile.connectWalletDesc': 'Please connect wallet to view profile',

    // Roadmap
    'roadmap.title': 'Project Roadmap',
    'roadmap.subtitle': 'Our path to success',
    'roadmap.q4_2025': 'Q4 2025',
    'roadmap.launch': 'Platform Launch',
    'roadmap.launchItems': 'Platform launch|Start fundraising|Purchase first cars',
    'roadmap.dec_jan': 'December 2025 - January 2026',
    'roadmap.fundraising': 'Fundraising',
    'roadmap.fundraisingItems': 'Reach ฿2.8M|Fill all 6-7 slots|Activate all vehicles',
    'roadmap.jan_2026': 'January 2026',
    'roadmap.roundClose': 'Round Close',
    'roadmap.roundCloseItems': 'Close fundraising|Company registration|Start operations',
    'roadmap.feb_2026': 'February 2026',
    'roadmap.legal': 'Legal Setup',
    'roadmap.legalItems': 'Legal entity registration|Vehicle registration|Licenses and permits',
    'roadmap.mar_2026': 'March 2026',
    'roadmap.firstPayouts': 'First Payouts',
    'roadmap.firstPayoutsItems': 'Launch rentals|First investor payouts|Operations stabilization',
    'roadmap.jul_2026': 'July 2026',
    'roadmap.expansion': 'Expansion',
    'roadmap.expansionItems': 'Buyout 6-month investments|Fleet expansion|New locations',
    'roadmap.oct_2026': 'October 2026',
    'roadmap.newProducts': 'New Products',
    'roadmap.newProductsItems': 'Launch new services|Hotel partnerships|Brand development',
    'roadmap.2027': '2027',
    'roadmap.continued': 'Continued Growth',
    'roadmap.continuedItems': 'Business scaling|New investment rounds|International expansion',
    'roadmap.disclaimer': 'This is an approximate development plan. Actual timelines may vary depending on market conditions and other factors.',
    
    // Alert
    'alert.connectWallet': 'Please connect wallet to invest',

    // Header extras
    'header.subtitle': 'Rental Investments',
    'header.signing': 'Signing...',
    'header.login': 'Login',
    'header.lightTheme': 'Light',
    'header.darkTheme': 'Dark',
    'header.authError': 'Failed to authorize wallet. Please try again.',
    'header.logging': 'Logging in...',

    // Contact
    'contact.title': 'Contact Us',
    'contact.description': 'Get in touch with our team for support, partnerships, or general inquiries',
    'contact.messageSent': 'Message Sent!',
    'contact.thankYou': 'Thank you for reaching out. We\'ll get back to you within 24 hours.',
    'contact.yourName': 'Your Name',
    'contact.emailAddress': 'Email Address',
    'contact.subject': 'Subject',
    'contact.selectSubject': 'Select a subject',
    'contact.generalInquiry': 'General Inquiry',
    'contact.technicalSupport': 'Technical Support',
    'contact.partnership': 'Partnership',
    'contact.securityIssue': 'Security Issue',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us how we can help you...',
    'contact.sendMessage': 'Send Message',
    'contact.quickContact': 'Quick Contact',
    'contact.email': 'Email',
    'contact.joinCommunity': 'Join Community',
    'contact.followUs': 'Follow Us',
    'contact.supportHours': 'Support Hours',
    'contact.mondayFriday': 'Monday - Friday',
    'contact.remoteFirst': 'Remote First',
    'contact.globalTeam': 'Global Team',

    // Chat
    'chat.agentName': 'TMC Consultant',
    'chat.consultantOnline': 'Online',
    'chat.typing': 'Typing...',
    'chat.end': 'End',
    'chat.endChat': 'End chat',
    'chat.endChatConfirm': 'Are you sure you want to end the chat?',
    'chat.contactManager': 'Contact manager',
    'chat.waitingForManager': 'Waiting for manager...',
    'chat.startChat': 'Start chat',
    'chat.introduceYourself': 'Please introduce yourself',
    'chat.yourName': 'Your name',
    'chat.namePlaceholder': 'Enter name',
    'chat.emailOptional': 'Email (optional)',
    'chat.welcomeMessage': 'Hello, {name}! How can I help you?',
    'chat.managerRequestSent': 'Manager request sent. Please wait for response.',

    // Dashboard
    'dashboard.myDashboard': 'Investor Dashboard',
    'dashboard.manageInvestments': 'Manage your assets and track your profit',
    'dashboard.invested': 'Total Invested',
    'dashboard.earned': 'Total Earned',
    'dashboard.totalBalance': 'Total Balance',
    'dashboard.active': 'Active Tiers',
    'dashboard.earningsProjection': 'Earnings Projection',
    'dashboard.balanceByMonth': 'Capital growth over time',
    'dashboard.balance': 'Balance',
    'dashboard.monthlyIncome': 'Monthly Income',
    'dashboard.accumulated': 'Accumulated',
    'dashboard.withdraw': 'Withdraw',
    'dashboard.staking': 'Staking',
    'dashboard.carShare': 'Car Share',
    'dashboard.connectWallet': 'Connect Wallet',
    'dashboard.connectToView': 'Please connect your MetaMask to view your investments',
    'dashboard.loading': 'Loading data...',
    'dashboard.noInvestments': 'No investments found',
    'dashboard.startInvestingHere': 'Your investments will appear here after payment',
    'dashboard.withdrawn': 'Withdrawn',
    'dashboard.withdrawalTypeLabel': 'Withdrawal type:',
    'dashboard.withdrawAll': 'All funds',
    'dashboard.withdrawAllDesc': 'Principal + accumulated earnings',
    'dashboard.withdrawEarnings': 'Earnings only',
    'dashboard.withdrawEarningsDesc': 'Accumulated profit, principal remains',
    'dashboard.withdrawPrincipal': 'Principal only',
    'dashboard.withdrawPrincipalDesc': 'Initial investment amount',
    'dashboard.baseAmount': 'Amount:',
    'dashboard.baseFee': 'Base fee (3%):',
    'dashboard.earlyFeeMayApply': '+ early withdrawal fee (5%) if lock period not expired',
    'dashboard.estimatedAmount': 'Estimated amount to receive:',
    'dashboard.withdrawalWallet': 'Withdrawal wallet (optional)',
    'dashboard.withdrawalWalletHint': 'If not specified, connected wallet will be used',
    'dashboard.submitWithdrawal': 'Submit request',
    'dashboard.processing': 'Processing...',
    'dashboard.withdrawalSuccess': 'Request sent!',
    'dashboard.withdrawalSuccessDesc': 'Your withdrawal request will be processed by admin within 48 hours.',
    'dashboard.withdrawalPending': 'Pending approval...',
    'dashboard.walletRequired': 'Please connect wallet or enter withdrawal address',
    'dashboard.invalidWalletFormat': 'Invalid wallet address format',
    'dashboard.withdrawalError': 'Error submitting withdrawal request',

    // Modal
    'modal.agreementTitle': 'INVESTMENT AGREEMENT (OFFER)',
    'modal.agreementIntro': 'Please read the terms of participation in the Thailand My Car project carefully before making a deposit.',
    'modal.agreementNature': 'Nature of transaction:',
    'modal.agreementNatureText': 'You are contributing funds for the joint acquisition and operation of vehicles. This is not a bank deposit.',
    'modal.agreementNotPublic': 'Private offering',
    'modal.agreementRisks': 'Risks:',
    'modal.agreementRisksText': 'Investing in car rental involves market risks, equipment wear and force majeure.',
    'modal.agreementNotGuaranteed': 'Returns are not 100% guaranteed',
    'modal.agreementRisksNote': ' However, all vehicles are insured.',
    'modal.agreementReturn': 'Return of funds:',
    'modal.agreementReturnText': 'Return conditions depend on the selected tier (6 months or ownership).',
    'modal.agreementTaxes': 'Taxes:',
    'modal.agreementTaxesText': 'The investor is solely responsible for paying taxes in their jurisdiction.',
    'modal.agreementDisputes': 'Disputes:',
    'modal.agreementDisputesText': 'All disputes are resolved through negotiation or according to Thai law.',
    'modal.agreementAge': 'Age:',
    'modal.agreementAgeText': 'You must be at least',
    'modal.agreementAgeYears': '18 years old',
    'modal.agreementData': 'Data:',
    'modal.agreementDataText': 'You agree to the processing of minimum necessary data for investment accounting.',
    'modal.agreementRoadmap': 'Roadmap:',
    'modal.agreementRoadmapText': 'Timelines in the roadmap are approximate.',
    'modal.agreementVersion': 'Version 1.0.4 • 2025',
    'modal.scrollDown': 'Scroll down to read',
    'modal.agreeTerms': 'I agree to the terms and understand the risks',
    'modal.scrollToEnd': 'Read the agreement to the end',
    'modal.continue': 'Continue',
    'modal.readAgreement': 'Read the agreement',
    'modal.amount': 'Investment amount',
    'modal.minAmount': 'Minimum amount',
    'modal.expectedReturn': 'Expected return (6 mo)',
    'modal.expectedReturnCar': 'Expected bonus or car',
    'modal.next': 'Next',
    'modal.payViaWallet': 'Pay via wallet',
    'modal.confirmInWallet': 'Confirm in MetaMask',
    'modal.applicationCreated': 'Application created!',
    'modal.done': 'Done',
    'modal.back': 'Back',
  },
  th: {
    // Header
    'header.home': 'หน้าแรก',
    'header.about': 'เกี่ยวกับ',
    'header.invest': 'ลงทุน',
    'header.dashboard': 'แดชบอร์ด',
    'header.roadmap': 'แผนงาน',
    'header.profile': 'โปรไฟล์',
    'header.connectWallet': 'เชื่อมต่อกระเป๋า',
    'header.disconnect': 'ตัดการเชื่อมต่อ',
    
    // Hero
    'hero.title': 'ลงทุนในธุรกิจให้เช่ารถโตโยต้าในพัทยา',
    'hero.mainTitle': 'ลงทุน',
    'hero.mainTitleLine2': 'ในธุรกิจให้เช่ารถ',
    'hero.subtitle': 'รายได้แบบพาสซีฟจากการเช่ารถในไทยด้วยการลงทุนคริปโต',
    'hero.carsInfo': 'รถโตโยต้า • ตั้งแต่ $1,000 • 1.7%/เดือน',
    'hero.orOwnership': 'หรือเป็นเจ้าของรถ',
    'hero.invested': 'ลงทุนแล้ว',
    'hero.investors': 'นักลงทุน',
    'hero.cars': 'รถยนต์',
    'hero.investNow': 'ลงทุนตอนนี้',
    'hero.collected': 'รวบรวมจาก',
    'hero.monthlyReturn': '/เดือน',
    'hero.income': 'รายได้',
    'hero.forecast': 'คาดการณ์',

    // Investment Tiers
    'tiers.title': 'ระดับการลงทุน',
    'tiers.options': 'ตัวเลือกการเข้าร่วม',
    'tiers.subtitle': 'เลือกตัวเลือกการลงทุนของคุณ',
    'tiers.from': 'จาก',
    'tiers.selectTier': 'เลือกระดับ',
    'tiers.connectWallet': 'เชื่อมต่อกระเป๋า',
    'tiers.staking': 'การสเตกกิ้ง',
    'tiers.stakingBadge': 'สูงสุด 1.7%/เดือน',
    'tiers.stakingDesc': 'รายได้แบบพาสซีฟพร้อมเงื่อนไขการถอนที่ยืดหยุ่น',
    'tiers.carsLeft': 'คันที่เหลือ',
    'tiers.minInvestment': 'การลงทุนขั้นต่ำ',
    'tiers.stakingFeature1': '1.7% ต่อเดือน (20.4% ต่อปี)',
    'tiers.stakingFeature2': 'ถอนได้ทุกเมื่อ',
    'tiers.stakingFeature3': 'ค่าธรรมเนียม 5% สำหรับการถอนก่อน 6 เดือน',
    'tiers.stakingFeature4': 'ดอกเบี้ยสะสมรายเดือน',
    'tiers.carShare': 'ส่วนแบ่งรถยนต์',
    'tiers.carShareDesc': 'รับความเป็นเจ้าของรถหรือผลตอบแทนที่รับประกัน',
    'tiers.carShareFeature1': 'หลัง 6 เดือน: ผลตอบแทน +20% หรือรอรถ',
    'tiers.carShareFeature2': 'เป็นเจ้าของรถหลังชำระเงินกู้',
    'tiers.carShareFeature3': 'ลำดับความสำคัญ: มาก่อนได้ก่อน',
    'tiers.carShareFeature4': 'สามารถเปลี่ยนตัวเลือกก่อนปิดสินเชื่อ',
    'tiers.invest': 'ลงทุน',
    'tiers.currencies': 'สกุลเงินที่ยอมรับ:',
    'tiers.networkFee': 'ค่าธรรมเนียมเครือข่าย:',
    'tiers.deposit': 'ฝาก:',
    'tiers.directToWallet': 'โดยตรงไปยังกระเป๋าเงินขององค์กร',

    // About
    'about.title': 'เกี่ยวกับโครงการ',
    'about.subtitle': 'Thailand My Car เป็นแพลตฟอร์มนวัตกรรมสำหรับการลงทุนในธุรกิจให้เช่ารถโตโยต้าในพัทยา',
    'about.description': 'ธุรกิจให้เช่ารถที่ดำเนินงานอยู่ในพัทยาพร้อมผลกำไรที่พิสูจน์แล้ว',
    'about.cars': 'กองรถ',
    'about.carsSubtitle': 'รถยนต์ภายใต้การจัดการ',
    'about.newToyotaCars': 'รถโตโยต้าใหม่',
    'about.stableMonthlyFlow': 'รายได้ประจำเดือนที่มั่นคง',
    'about.fleetOccupancy': 'อัตราการใช้งานรถ 2025',
    'about.touristCenter': 'ศูนย์กลางการท่องเที่ยว',
    'about.monthlyIncome': 'รายได้',
    'about.monthlyIncomeSubtitle': 'รายได้ต่อเดือนที่มั่นคง',
    'about.occupancy': 'อัตราการเช่า',
    'about.occupancySubtitle': 'อัตราการเช่าเฉลี่ย',
    'about.location': 'สถานที่',
    'about.locationValue': 'พัทยา',
    'about.locationSubtitle': 'ศูนย์กลางการท่องเที่ยวของไทย',
    'about.growthTitle': 'ประวัติการเติบโต',
    'about.growthHistory': 'ประวัติการเติบโตของบริษัท',
    'about.carsUnit': 'คัน',
    'about.cars3': '3 คัน',
    'about.cars6': '6 คัน',
    'about.cars8': '8 คัน',
    'about.launch': 'เปิดตัวโครงการ',
    'about.start': 'เริ่มต้น',
    'about.growth': 'เติบโต',
    'about.now': 'ตอนนี้',
    'about.insurance': 'การประกันภัย',
    'about.insuranceDesc': 'รถยนต์ทุกคันมีประกันภัยชั้นหนึ่งเพื่อการคุ้มครองนักลงทุนสูงสุด',
    'about.insuranceFullDesc': 'ประกันภัยชั้น 1 เต็มรูปแบบสำหรับรถยนต์และผู้โดยสาร',
    'about.insurancePoint1': 'ความคุ้มครองความเสียหายของรถยนต์เต็มรูปแบบ',
    'about.insurancePoint2': 'การโจรกรรมและการกระทำโดยประสงค์ร้าย',
    'about.insurancePoint3': 'ภัยธรรมชาติ (น้ำท่วม, ไฟไหม้)',
    'about.insurancePoint4': 'ค่ารักษาพยาบาลสำหรับผู้ขับขี่และผู้โดยสาร',
    'about.insurancePoint5': 'ความรับผิดต่อบุคคลที่สาม',
    'about.insurancePoint6': 'ช่วยเหลือฉุกเฉินบนท้องถนน 24/7',
    'about.transparency': 'ความโปร่งใส',
    'about.transparencyDesc': 'รายงานการเช่าและการจ่ายเงินเต็มรูปแบบผ่านแดชบอร์ดและสมาร์ทคอนแทรค',
    'about.transparencyFullDesc': 'รายงานประจำเดือนและการเข้าถึงเมตริกแบบเรียลไทม์',
    'about.experience': 'ประสบการณ์',
    'about.experienceDesc': 'ประสบการณ์กว่า 5 ปีในตลาดเช่ารถในไทย รับประกันประสิทธิภาพการจัดการ',
    'about.experienceFullDesc': 'ดำเนินงานสำเร็จมากกว่า 2 ปีในตลาดเช่ารถไทย',
    'about.fleetTitle': 'กองรถโตโยต้าของเรา',
    'about.fleetDesc': 'เราใช้เฉพาะรถ Toyota รุ่นที่น่าเชื่อถือและเป็นที่นิยมเพื่อให้มั่นใจในสภาพคล่องสูง',
    'about.velozName': 'Toyota Veloz',
    'about.velozDesc': 'ครอสโอเวอร์ 7 ที่นั่งระดับพรีเมียม',
    'about.yarisName': 'Toyota Yaris',
    'about.yarisDesc': 'รถซีดานขนาดกะทัดรัดสำหรับเมือง',
    
    // Footer
    'footer.description': 'ลงทุนในธุรกิจให้เช่ารถในประเทศไทย',
    'footer.contacts': 'ติดต่อ',
    'footer.rights': 'สงวนลิขสิทธิ์',
    'footer.disclaimer': 'การลงทุนมีความเสี่ยง ปรึกษาผู้เชี่ยวชาญ',
    
    // Cookies
    'cookies.message': 'เราใช้คุกกี้เพื่อปรับปรุงประสบการณ์ของคุณบนเว็บไซต์ของเรา',
    'cookies.accept': 'ยอมรับ',
    'cookies.decline': 'ปฏิเสธ',
    
    // Profile
    'profile.back': 'กลับ',
    'profile.yourProfile': 'โปรไฟล์ของคุณ',
    'profile.memberSince': 'สมาชิกตั้งแต่',
    'profile.totalInvested': 'ลงทุนทั้งหมด',
    'profile.investments': 'การลงทุน',
    'profile.activeInvestments': 'ที่ใช้งานอยู่',
    'profile.inBaht': 'เป็นบาท',
    'profile.personalInfo': 'ข้อมูลส่วนตัว',
    'profile.name': 'ชื่อ',
    'profile.namePlaceholder': 'ชื่อของคุณ',
    'profile.bio': 'ประวัติ',
    'profile.bioPlaceholder': 'บอกเล่าเกี่ยวกับตัวคุณ...',
    'profile.saveProfile': 'บันทึกโปรไฟล์',
    'profile.saving': 'กำลังบันทึก...',
    'profile.updateSuccess': 'อัพเดทโปรไฟล์สำเร็จ',
    'profile.loadError': 'ไม่สามารถโหลดโปรไฟล์ได้',
    'profile.saveError': 'ไม่สามารถบันทึกโปรไฟล์ได้',
    'profile.connectWallet': 'เชื่อมต่อกระเป๋า',
    'profile.connectWalletDesc': 'กรุณาเชื่อมต่อกระเป๋าเพื่อดูโปรไฟล์',

    // Roadmap
    'roadmap.title': 'แผนงานโครงการ',
    'roadmap.subtitle': 'เส้นทางสู่ความสำเร็จของเรา',
    'roadmap.q4_2025': 'ไตรมาส 4 2568',
    'roadmap.launch': 'เปิดตัวแพลตฟอร์ม',
    'roadmap.launchItems': 'เปิดตัวแพลตฟอร์ม|เริ่มระดมทุน|ซื้อรถคันแรก',
    'roadmap.dec_jan': 'ธันวาคม 2568 - มกราคม 2569',
    'roadmap.fundraising': 'ระดมทุน',
    'roadmap.fundraisingItems': 'บรรลุเป้า ฿2.8M|เติมเต็มทุกช่อง 6-7|เปิดใช้งานรถทั้งหมด',
    'roadmap.jan_2026': 'มกราคม 2569',
    'roadmap.roundClose': 'ปิดรอบ',
    'roadmap.roundCloseItems': 'ปิดการระดมทุน|จดทะเบียนบริษัท|เริ่มดำเนินงาน',
    'roadmap.feb_2026': 'กุมภาพันธ์ 2569',
    'roadmap.legal': 'จัดการด้านกฎหมาย',
    'roadmap.legalItems': 'จดทะเบียนนิติบุคคล|จดทะเบียนรถยนต์|ใบอนุญาต',
    'roadmap.mar_2026': 'มีนาคม 2569',
    'roadmap.firstPayouts': 'จ่ายเงินครั้งแรก',
    'roadmap.firstPayoutsItems': 'เริ่มให้เช่า|จ่ายเงินนักลงทุนครั้งแรก|ทำให้ดำเนินงานมั่นคง',
    'roadmap.jul_2026': 'กรกฎาคม 2569',
    'roadmap.expansion': 'ขยายธุรกิจ',
    'roadmap.expansionItems': 'ซื้อคืนการลงทุน 6 เดือน|ขยายกองรถ|สถานที่ใหม่',
    'roadmap.oct_2026': 'ตุลาคม 2569',
    'roadmap.newProducts': 'ผลิตภัณฑ์ใหม่',
    'roadmap.newProductsItems': 'เปิดบริการใหม่|พันธมิตรโรงแรม|พัฒนาแบรนด์',
    'roadmap.2027': '2570',
    'roadmap.continued': 'เติบโตต่อเนื่อง',
    'roadmap.continuedItems': 'ขยายธุรกิจ|รอบลงทุนใหม่|ขยายต่างประเทศ',
    'roadmap.disclaimer': 'นี่คือแผนการพัฒนาโดยประมาณ ระยะเวลาจริงอาจแตกต่างไปตามสภาพตลาดและปัจจัยอื่นๆ',
    
    // Alert
    'alert.connectWallet': 'กรุณาเชื่อมต่อกระเป๋าเพื่อลงทุน',

    // Header extras
    'header.subtitle': 'การลงทุนในรถเช่า',
    'header.signing': 'กำลังลงนาม...',
    'header.login': 'เข้าสู่ระบบ',
    'header.lightTheme': 'สว่าง',
    'header.darkTheme': 'มืด',
    'header.authError': 'ไม่สามารถยืนยันกระเป๋าเงินได้ กรุณาลองอีกครั้ง',
    'header.logging': 'กำลังเข้าสู่ระบบ...',

    // Contact
    'contact.title': 'ติดต่อเรา',
    'contact.description': 'ติดต่อทีมงานของเราสำหรับการสนับสนุน พันธมิตร หรือคำถามทั่วไป',
    'contact.messageSent': 'ส่งข้อความแล้ว!',
    'contact.thankYou': 'ขอบคุณที่ติดต่อเรา เราจะตอบกลับภายใน 24 ชั่วโมง',
    'contact.yourName': 'ชื่อของคุณ',
    'contact.emailAddress': 'ที่อยู่อีเมล',
    'contact.subject': 'หัวข้อ',
    'contact.selectSubject': 'เลือกหัวข้อ',
    'contact.generalInquiry': 'คำถามทั่วไป',
    'contact.technicalSupport': 'ฝ่ายสนับสนุนด้านเทคนิค',
    'contact.partnership': 'พันธมิตร',
    'contact.securityIssue': 'ปัญหาความปลอดภัย',
    'contact.other': 'อื่นๆ',
    'contact.message': 'ข้อความ',
    'contact.messagePlaceholder': 'บอกเราว่าเราช่วยคุณได้อย่างไร...',
    'contact.sendMessage': 'ส่งข้อความ',
    'contact.quickContact': 'ติดต่อด่วน',
    'contact.email': 'อีเมล',
    'contact.joinCommunity': 'เข้าร่วมชุมชน',
    'contact.followUs': 'ติดตามเรา',
    'contact.supportHours': 'เวลาทำการ',
    'contact.mondayFriday': 'จันทร์ - ศุกร์',
    'contact.remoteFirst': 'ทำงานระยะไกล',
    'contact.globalTeam': 'ทีมระดับโลก',

    // Chat
    'chat.agentName': 'ที่ปรึกษา TMC',
    'chat.consultantOnline': 'ออนไลน์',
    'chat.typing': 'กำลังพิมพ์...',
    'chat.end': 'จบ',
    'chat.endChat': 'จบแชท',
    'chat.endChatConfirm': 'คุณแน่ใจหรือไม่ว่าต้องการจบแชท?',
    'chat.contactManager': 'ติดต่อผู้จัดการ',
    'chat.waitingForManager': 'รอผู้จัดการ...',
    'chat.startChat': 'เริ่มแชท',
    'chat.introduceYourself': 'กรุณาแนะนำตัวเอง',
    'chat.yourName': 'ชื่อของคุณ',
    'chat.namePlaceholder': 'ใส่ชื่อ',
    'chat.emailOptional': 'อีเมล (ไม่บังคับ)',
    'chat.welcomeMessage': 'สวัสดี {name}! ฉันช่วยอะไรได้บ้าง?',
    'chat.managerRequestSent': 'ส่งคำขอผู้จัดการแล้ว กรุณารอการตอบกลับ',

    // Dashboard
    'dashboard.myDashboard': 'แผงควบคุมนักลงทุน',
    'dashboard.manageInvestments': 'จัดการสินทรัพย์และติดตามกำไรของคุณ',
    'dashboard.invested': 'ลงทุนทั้งหมด',
    'dashboard.earned': 'รายได้ทั้งหมด',
    'dashboard.totalBalance': 'ยอดคงเหลือทั้งหมด',
    'dashboard.active': 'การลงทุนที่ใช้งานอยู่',
    'dashboard.earningsProjection': 'ประมาณการรายได้',
    'dashboard.balanceByMonth': 'การเติบโตของทุนเมื่อเวลาผ่านไป',
    'dashboard.balance': 'ยอดคงเหลือ',
    'dashboard.monthlyIncome': 'รายได้ต่อเดือน',
    'dashboard.accumulated': 'สะสมแล้ว',
    'dashboard.withdraw': 'ถอนเงิน',
    'dashboard.staking': 'การสเตกกิ้ง',
    'dashboard.carShare': 'ส่วนแบ่งรถยนต์',
    'dashboard.connectWallet': 'เชื่อมต่อกระเป๋า',
    'dashboard.connectToView': 'กรุณาเชื่อมต่อ MetaMask เพื่อดูการลงทุนของคุณ',
    'dashboard.loading': 'กำลังโหลดข้อมูล...', 
    'dashboard.noInvestments': 'ไม่พบการลงทุน',
    'dashboard.startInvestingHere': 'การลงทุนของคุณจะปรากฏที่นี่หลังจากการชำระเงิน',
    'dashboard.withdrawn': 'ถอนแล้ว',
    'dashboard.withdrawalTypeLabel': 'ประเภทการถอน:',
    'dashboard.withdrawAll': 'เงินทั้งหมด',
    'dashboard.withdrawAllDesc': 'เงินต้น + ผลตอบแทนสะสม',
    'dashboard.withdrawEarnings': 'ผลตอบแทนเท่านั้น',
    'dashboard.withdrawEarningsDesc': 'กำไรสะสม เงินต้นยังคงอยู่',
    'dashboard.withdrawPrincipal': 'เงินต้นเท่านั้น',
    'dashboard.withdrawPrincipalDesc': 'จำนวนเงินลงทุนเริ่มต้น',
    'dashboard.baseAmount': 'จำนวนเงิน:',
    'dashboard.baseFee': 'ค่าธรรมเนียมพื้นฐาน (3%):',
    'dashboard.earlyFeeMayApply': '+ ค่าธรรมเนียมถอนก่อนกำหนด (5%) หากยังไม่ครบกำหนด',
    'dashboard.estimatedAmount': 'จำนวนเงินโดยประมาณที่จะได้รับ:',
    'dashboard.withdrawalWallet': 'กระเป๋าเงินสำหรับถอน (ไม่บังคับ)',
    'dashboard.withdrawalWalletHint': 'หากไม่ระบุ จะใช้กระเป๋าเงินที่เชื่อมต่ออยู่',
    'dashboard.submitWithdrawal': 'ส่งคำขอ',
    'dashboard.processing': 'กำลังดำเนินการ...',
    'dashboard.withdrawalSuccess': 'ส่งคำขอแล้ว!',
    'dashboard.withdrawalSuccessDesc': 'คำขอถอนเงินของคุณจะได้รับการพิจารณาโดยผู้ดูแลภายใน 48 ชั่วโมง',
    'dashboard.withdrawalPending': 'รอการอนุมัติ...',
    'dashboard.walletRequired': 'โปรดเชื่อมต่อกระเป๋าเงินหรือใส่ที่อยู่สำหรับถอน',
    'dashboard.invalidWalletFormat': 'รูปแบบที่อยู่กระเป๋าเงินไม่ถูกต้อง',
    'dashboard.withdrawalError': 'เกิดข้อผิดพลาดในการส่งคำขอถอนเงิน',

    // Modal
    'modal.agreementTitle': 'ข้อตกลงการลงทุน (ข้อเสนอ)',
    'modal.agreementIntro': 'กรุณาอ่านเงื่อนไขการเข้าร่วมโครงการ THAILAND MY CAR อย่างละเอียด',
    'modal.agreementNature': 'ลักษณะของการทำธุรกรรม:',
    'modal.agreementNatureText': 'นี่ไม่ใช่โทเค็น การลงทุน NFT หรือหุ้นในบริษัท การโอนเงินเป็นเงินกู้ที่มีหลักประกันซึ่งให้สิทธิ์ในการชำระคืนเงินลงทุนพร้อมผลตอบแทนคงที่ 20% หลังจากหกเดือนหรือโอนความเป็นเจ้าของรถยนต์',
    'modal.agreementRisks': 'ความเสี่ยง:',
    'modal.agreementRisksText': 'การลงทุนนี้มีความเสี่ยง รวมถึงความเสี่ยงจากการสูญเสียเงินลงทุนทั้งหมดหรือบางส่วน คุณยืนยันว่าคุณยอมรับความเสี่ยงเหล่านี้อย่างมีสติ',
    'modal.agreementInvestorResponsibility': 'ความรับผิดชอบของนักลงทุน:',
    'modal.agreementInvestorResponsibilityText': 'คุณยืนยันว่าจำนวนเงินลงทุนไม่มาจากแหล่งผิดกฎหมายและคุณมีสิทธิ์ทำธุรกรรมนี้ ผู้จัดงานไม่รับผิดชอบต่อผลกระทบทางภาษีจากด้านนักลงทุน',
    'modal.agreementPaymentMethod': 'วิธีการชำระเงิน:',
    'modal.agreementPaymentMethodText': 'การชำระเงินทำในสกุลเงินดิจิทัล (USDT, USDC) โดยโอนโดยตรงไปยังกระเป๋าเงินของบริษัท การยืนยันจะส่งหลังจากได้รับและตรวจสอบการทำธุรกรรม',
    'modal.agreementReturns': 'ผลตอบแทน:',
    'modal.agreementReturnsText': 'ผลตอบแทน 20% ตลอดหกเดือนไม่รับประกันและขึ้นอยู่กับผลลัพธ์จริงของการให้เช่ารถ ตัวเลือกการโอนกรรมสิทธิ์รถจะถูกเปิดใช้งานหลังจากชำระเงินเต็มจำนวน',
    'modal.agreementTerms': 'การยกเลิกและเงื่อนไข:',
    'modal.agreementTermsText': 'กรณีถอนก่อนกำหนด (ก่อน 6 เดือน) - ค่าธรรมเนียม 5% เงื่อนไขโดยละเอียดจะระบุในสัญญา',
    'modal.agreementAcceptance': 'การยอมรับเงื่อนไข:',
    'modal.agreementAcceptanceText': 'การคลิกปุ่ม "ยืนยันการลงทุน" หรือ "ยอมรับเงื่อนไข" แสดงว่าคุณยืนยันว่าคุณอ่านและยอมรับเงื่อนไขทั้งหมดของข้อตกลงการลงทุนนี้',
    'modal.agreementJurisdiction': 'เขตอำนาจศาล:',
    'modal.agreementJurisdictionText': 'ความสัมพันธ์ระหว่างคู่สัญญาอยู่ภายใต้กฎหมายของประเทศไทย',
    'modal.agreementUpdates': 'การเปลี่ยนแปลงเงื่อนไข:',
    'modal.agreementUpdatesText': 'ผู้จัดงานขอสงวนสิทธิ์ในการเปลี่ยนแปลงเงื่อนไขการลงทุนตามสภาพตลาดและข้อจำกัดทางกฎหมาย',
    'modal.agreementTaxNote': 'การแจ้งเตือนภาษี:',
    'modal.agreementTaxNoteText': 'นักลงทุนมีหน้าที่รับผิดชอบในการรายงานรายได้ตามกฎหมายภาษีของประเทศที่ตนอาศัยอยู่',
    'modal.iAgree': 'ฉันได้อ่านและยอมรับเงื่อนไขของข้อตกลงการลงทุน',
    'modal.scrollToEnd': 'อ่านข้อตกลงจนจบ',
    'modal.continue': 'ดำเนินการต่อ',
    'modal.readAgreement': 'อ่านข้อตกลง',
    'modal.amount': 'จำนวนเงินลงทุน',
    'modal.minAmount': 'จำนวนขั้นต่ำ',
    'modal.expectedReturn': 'ผลตอบแทนที่คาดหวัง (6 เดือน)',
    'modal.expectedReturnCar': 'โบนัสที่คาดหวังหรือรถยนต์',
    'modal.next': 'ถัดไป',
    'modal.payViaWallet': 'ชำระผ่านกระเป๋าเงิน',
    'modal.confirmInWallet': 'ยืนยันใน MetaMask',
    'modal.applicationCreated': 'สร้างใบสมัครแล้ว!',
    'modal.done': 'เสร็จสิ้น',
    'modal.back': 'กลับ',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ru');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['ru', 'en', 'th'].includes(savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
