import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simplified translations - for full version, load from GitHub
const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Header
    'header.home': 'Главная',
    'header.about': 'О проекте',
    'header.invest': 'Инвестировать',
    'header.dashboard': 'Дэшборд',
    'header.roadmap': 'Roadmap',
    'header.profile': 'Профиль',
    'header.connectWallet': 'Подключить кошелек',
    'header.disconnect': 'Отключить',
    
    // Hero
    'hero.title': 'Инвестируйте в рентал-бизнес Toyota в Паттайе',
    'hero.subtitle': 'Пассивный доход от аренды автомобилей в Таиланде с криптоинвестициями',
    'hero.invested': 'Инвестировано',
    'hero.investors': 'Инвесторов',
    'hero.cars': 'Автомобилей',
    'hero.investNow': 'Инвестировать сейчас',
    
    // Investment Tiers
    'tiers.title': 'Инвестиционные тиры',
    'tiers.subtitle': 'Выберите подходящий вариант инвестирования',
    'tiers.from': 'от',
    'tiers.selectTier': 'Выбрать тир',
    'tiers.connectWallet': 'Подключите кошелек',
    
    // About
    'about.title': 'О проекте',
    'about.subtitle': 'Thailand My Car — это инновационная платформа для инвестиций в рентал-бизнес автомобилей Toyota в Паттайе',
    'about.cars': 'Автопарк',
    'about.carsSubtitle': 'автомобилей в управлении',
    'about.monthlyIncome': 'Доход',
    'about.monthlyIncomeSubtitle': 'стабильный поток в месяц',
    'about.occupancy': 'Загрузка',
    'about.occupancySubtitle': 'средний показатель аренды',
    'about.location': 'Локация',
    'about.locationValue': 'Паттайя',
    'about.locationSubtitle': 'туристический центр Таиланда',
    'about.growthTitle': 'История роста',
    'about.cars3': '3 авто',
    'about.cars6': '6 авто',
    'about.cars8': '8 авто',
    'about.launch': 'Запуск проекта',
    'about.growth': 'Активное расширение',
    'about.now': 'Текущий этап',
    'about.insurance': 'Страхование',
    'about.insuranceDesc': 'Все автомобили застрахованы по первому классу для максимальной защиты инвесторов.',
    'about.transparency': 'Прозрачность',
    'about.transparencyDesc': 'Полная отчетность по аренде и выплатам через личный кабинет и смарт-контракты.',
    'about.experience': 'Опыт команды',
    'about.experienceDesc': 'Более 5 лет на рынке аренды автомобилей в Таиланде гарантируют эффективность управления.',
    'about.fleetTitle': 'Наш автопарк',
    'about.fleetDesc': 'Мы используем только надежные и популярные модели Toyota, обеспечивающие высокую ликвидность.',
    'about.velozDesc': 'Премиальный 7-местный кроссовер, идеален для семейных поездок и больших групп.',
    'about.yarisDesc': 'Компактный и экономичный хэтчбек, самый популярный выбор для городских поездок.',
    
    // Footer
    'footer.description': 'Инвестируйте в рентал-бизнес автомобилей в Таиланде',
    'footer.contacts': 'Контакты',
    'footer.rights': 'Все права защищены',
    'footer.disclaimer': 'Инвестиции сопряжены с рисками. Проконсультируйтесь со специалистом.',
    
    // Cookies
    'cookies.message': 'Мы используем cookies для улучшения вашего опыта на сайте.',
    'cookies.accept': 'Принять',
    'cookies.decline': 'Отклонить',
    
    // Profile
    'profile.back': 'Назад',
    'profile.yourProfile': 'Ваш профиль',
    'profile.memberSince': 'Участник с',
    'profile.totalInvested': 'Всего инвестировано',
    'profile.investments': 'Инвестиций',
    'profile.activeInvestments': 'Активные',
    'profile.inBaht': 'В батах',
    'profile.personalInfo': 'Личная информация',
    'profile.name': 'Имя',
    'profile.namePlaceholder': 'Ваше имя',
    'profile.bio': 'О себе',
    'profile.bioPlaceholder': 'Расскажите немного о себе...',
    'profile.saveProfile': 'Сохранить профиль',
    'profile.saving': 'Сохранение...',
    'profile.updateSuccess': 'Профиль успешно обновлен',
    'profile.connectWallet': 'Подключите кошелек',
    'profile.connectWalletDesc': 'Для просмотра профиля необходимо подключить кошелек',
    
    // Roadmap
    'roadmap.title': 'План развития проекта',
    'roadmap.subtitle': 'Наш путь к успеху',
    'roadmap.q4_2025': 'Q4 2025',
    'roadmap.launch': 'Запуск платформы',
    'roadmap.launchItems': 'Запуск платформы|Начало сбора инвестиций|Покупка первых автомобилей',
    'roadmap.dec_jan': 'Декабрь 2025 - Январь 2026',
    'roadmap.fundraising': 'Сбор средств',
    'roadmap.fundraisingItems': 'Достижение ฿2.8M|Полное заполнение 6-7 слотов|Активация всех автомобилей',
    'roadmap.jan_2026': 'Январь 2026',
    'roadmap.roundClose': 'Закрытие раунда',
    'roadmap.roundCloseItems': 'Закрытие сбора|Регистрация компании|Начало операций',
    'roadmap.feb_2026': 'Февраль 2026',
    'roadmap.legal': 'Юридическое оформление',
    'roadmap.legalItems': 'Регистрация юр. лица|Оформление автомобилей|Лицензии и разрешения',
    'roadmap.mar_2026': 'Март 2026',
    'roadmap.firstPayouts': 'Первые выплаты',
    'roadmap.firstPayoutsItems': 'Запуск аренды|Первые выплаты инвесторам|Стабилизация операций',
    'roadmap.jul_2026': 'Июль 2026',
    'roadmap.expansion': 'Расширение',
    'roadmap.expansionItems': 'Выкуп 6-месячных инвестиций|Расширение автопарка|Новые локации',
    'roadmap.oct_2026': 'Октябрь 2026',
    'roadmap.newProducts': 'Новые продукты',
    'roadmap.newProductsItems': 'Запуск новых услуг|Партнерство с отелями|Развитие бренда',
    'roadmap.2027': '2027',
    'roadmap.continued': 'Продолжение роста',
    'roadmap.continuedItems': 'Масштабирование бизнеса|Новые инвестиционные раунды|Международное расширение',
    // Dashboard
    'dashboard.myDashboard': 'Личный кабинет',
    'dashboard.manageInvestments': 'Управление вашими активами и отслеживание прибыли',
    'dashboard.invested': 'Инвестировано',
    'dashboard.earned': 'Начислено',
    'dashboard.totalBalance': 'Общий баланс',
    'dashboard.active': 'Активных тиров',
    'dashboard.earningsProjection': 'Прогноз доходности',
    'dashboard.balanceByMonth': 'Рост вашего капитала во времени',
    'dashboard.balance': 'Баланс',
    'dashboard.monthlyIncome': 'Доход в месяц',
    'dashboard.accumulated': 'Накоплено',
    'dashboard.withdraw': 'Вывести',
    'dashboard.staking': 'Стейкинг',
    'dashboard.carShare': 'Доля в авто',
    'dashboard.connectWallet': 'Подключите кошелек',
    'dashboard.connectToView': 'Чтобы увидеть свои инвестиции, необходимо авторизоваться через MetaMask',
    'dashboard.loading': 'Загрузка данных...', 
    'dashboard.noInvestments': 'Инвестиций не найдено',
    'dashboard.startInvestingHere': 'Ваши будущие инвестиции появятся здесь после оплаты',
    'dashboard.withdrawn': 'Выведено',
    'dashboard.withdrawalTypeLabel': 'Тип вывода:',
    'dashboard.withdrawAll': 'Все средства',
    'dashboard.withdrawAllDesc': 'Тело вклада + накопленные проценты',
    'dashboard.withdrawEarnings': 'Только проценты',
    'dashboard.withdrawEarningsDesc': 'Накопленный доход, тело остается',
    'dashboard.withdrawPrincipal': 'Только тело вклада',
    'dashboard.withdrawPrincipalDesc': 'Основная сумма инвестиции',
    'dashboard.baseAmount': 'Сумма:',
    'dashboard.baseFee': 'Базовая комиссия (3%):',
    'dashboard.earlyFeeMayApply': '+ комиссия за ранний вывод (5%) если не истек срок',
    'dashboard.estimatedAmount': 'Примерная сумма к получению:',
    'dashboard.withdrawalWallet': 'Кошелек для вывода (опционально)',
    'dashboard.withdrawalWalletHint': 'Если не указан, будет использован подключенный кошелек',
    'dashboard.submitWithdrawal': 'Отправить запрос',
    'dashboard.processing': 'Обработка...',
    'dashboard.withdrawalSuccess': 'Запрос отправлен!',
    'dashboard.withdrawalSuccessDesc': 'Ваш запрос на вывод средств будет обработан администратором в течение 48 часов.',
    'dashboard.withdrawalPending': 'Ожидает одобрения...',
    'dashboard.walletRequired': 'Пожалуйста, подключите кошелек или введите адрес для вывода',
    'dashboard.invalidWalletFormat': 'Неверный формат адреса кошелька',
    'dashboard.withdrawalError': 'Ошибка при отправке запроса на вывод',

    // Alert
    'alert.connectWallet': 'Пожалуйста, подключите кошелек для инвестирования',

    // Chat
    'chat.agentName': 'Консультант TMC',
    'chat.consultantOnline': 'Онлайн',
    'chat.typing': 'Печатает...',
    'chat.end': 'Завершить',
    'chat.endChat': 'Завершить чат',
    'chat.endChatConfirm': 'Вы уверены, что хотите завершить чат?',
    'chat.contactManager': 'Связаться с менеджером',
    'chat.waitingForManager': 'Ожидание менеджера...',
    'chat.startChat': 'Начать чат',
    'chat.introduceYourself': 'Представьтесь, пожалуйста',
    'chat.yourName': 'Ваше имя',
    'chat.namePlaceholder': 'Введите имя',
    'chat.emailOptional': 'Email (необязательно)',
    'chat.welcomeMessage': 'Здравствуйте, {name}! Чем могу помочь?',
    'chat.managerRequestSent': 'Запрос менеджеру отправлен. Ожидайте ответа.',

    // Modal
    'modal.agreementTitle': 'ИНВЕСТИЦИОННОЕ СОГЛАШЕНИЕ (ОФЕРТА)',
    'modal.agreementIntro': 'Пожалуйста, внимательно ознакомьтесь с условиями участия в проекте Thailand My Car перед внесением средств.',
    'modal.agreementNature': 'Характер сделки:',
    'modal.agreementNatureText': 'Вы вносите средства для совместного приобретения и эксплуатации автомобилей. Это не является банковским вкладом.',
    'modal.agreementNotPublic': 'Частное предложение',
    'modal.agreementRisks': 'Риски:',
    'modal.agreementRisksText': 'Инвестиции в аренду авто связаны с рыночными рисками, износом техники и форс-мажорами.',
    'modal.agreementNotGuaranteed': 'Доход не гарантирован на 100%',
    'modal.agreementRisksNote': ' Однако все авто застрахованы.',
    'modal.agreementReturn': 'Возврат средств:',
    'modal.agreementReturnText': 'Условия возврата зависят от выбранного тира (6 месяцев или владение).',
    'modal.agreementTaxes': 'Налоги:',
    'modal.agreementTaxesText': 'Инвестор самостоятельно несет ответственность за уплату налогов в своей юрисдикции.',
    'modal.agreementDisputes': 'Споры:',
    'modal.agreementDisputesText': 'Все споры решаются путем переговоров или согласно законодательству Таиланда.',
    'modal.agreementAge': 'Возраст:',
    'modal.agreementAgeText': 'Вам должно быть не менее',
    'modal.agreementAgeYears': '18 лет',
    'modal.agreementData': 'Данные:',
    'modal.agreementDataText': 'Вы соглашаетесь на обработку минимально необходимых данных для учета инвестиции.',
    'modal.agreementRoadmap': 'Roadmap:',
    'modal.agreementRoadmapText': 'Сроки в дорожной карте являются ориентировочными.',
    'modal.agreementVersion': 'Версия 1.0.4 • 2025',
    'modal.scrollDown': 'Прокрутите вниз, чтобы прочитать',
    'modal.agreeTerms': 'Я согласен с условиями и осознаю риски',
    'modal.scrollToEnd': 'Прочтите соглашение до конца',
    'modal.continue': 'Продолжить',
    'modal.readAgreement': 'Прочтите соглашение',
    'modal.amount': 'Сумма инвестиции',
    'modal.expectedReturn': 'Ожидаемый доход (6 мес)',
    'modal.expectedReturnCar': 'Ожидаемый бонус или авто',
    'modal.next': 'Далее',
    'modal.payViaWallet': 'Оплатить через кошелек',
    'modal.confirmInWallet': 'Подтвердите в MetaMask',
    'modal.applicationCreated': 'Заявка создана!',
    'modal.done': 'Готово',
    'modal.back': 'Назад',
  },
  en: {
    // Header
    'header.home': 'Home',
    'header.about': 'About',
    'header.invest': 'Invest',
    'header.dashboard': 'Dashboard',
    'header.roadmap': 'Roadmap',
    'header.profile': 'Profile',
    'header.connectWallet': 'Connect Wallet',
    'header.disconnect': 'Disconnect',
    
    // Hero
    'hero.title': 'Invest in Toyota Rental Business in Pattaya',
    'hero.subtitle': 'Passive income from car rental in Thailand with crypto investments',
    'hero.invested': 'Invested',
    'hero.investors': 'Investors',
    'hero.cars': 'Cars',
    'hero.investNow': 'Invest Now',
    
    // Investment Tiers
    'tiers.title': 'Investment Tiers',
    'tiers.subtitle': 'Choose your investment option',
    'tiers.from': 'from',
    'tiers.selectTier': 'Select Tier',
    'tiers.connectWallet': 'Connect Wallet',
    
    // About
    'about.title': 'About Project',
    'about.subtitle': 'Thailand My Car is an innovative platform for investments in Toyota car rental business in Pattaya',
    'about.cars': 'Fleet',
    'about.carsSubtitle': 'cars under management',
    'about.monthlyIncome': 'Income',
    'about.monthlyIncomeSubtitle': 'stable monthly flow',
    'about.occupancy': 'Occupancy',
    'about.occupancySubtitle': 'average rental rate',
    'about.location': 'Location',
    'about.locationValue': 'Pattaya',
    'about.locationSubtitle': 'Thailand tourism hub',
    'about.growthTitle': 'Growth History',
    'about.cars3': '3 cars',
    'about.cars6': '6 cars',
    'about.cars8': '8 cars',
    'about.launch': 'Project Launch',
    'about.growth': 'Active Expansion',
    'about.now': 'Current Stage',
    'about.insurance': 'Insurance',
    'about.insuranceDesc': 'All cars are covered by first-class insurance for maximum investor protection.',
    'about.transparency': 'Transparency',
    'about.transparencyDesc': 'Full reporting on rentals and payouts via dashboard and smart contracts.',
    'about.experience': 'Team Experience',
    'about.experienceDesc': 'Over 5 years in Thailand car rental market guarantee management efficiency.',
    'about.fleetTitle': 'Our Fleet',
    'about.fleetDesc': 'We use only reliable and popular Toyota models ensuring high liquidity.',
    'about.velozDesc': 'Premium 7-seater MPV, perfect for family trips and large groups.',
    'about.yarisDesc': 'Compact and economical hatchback, the most popular choice for city trips.',
    
    // Footer
    'footer.description': 'Invest in car rental business in Thailand',
    'footer.contacts': 'Contacts',
    'footer.rights': 'All rights reserved',
    'footer.disclaimer': 'Investments carry risks. Consult with a specialist.',
    
    // Cookies
    'cookies.message': 'We use cookies to improve your experience on our site.',
    'cookies.accept': 'Accept',
    'cookies.decline': 'Decline',
    
    // Profile
    'profile.back': 'Back',
    'profile.yourProfile': 'Your Profile',
    'profile.memberSince': 'Member since',
    'profile.totalInvested': 'Total Invested',
    'profile.investments': 'Investments',
    'profile.activeInvestments': 'Active',
    'profile.inBaht': 'In Baht',
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Name',
    'profile.namePlaceholder': 'Your name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.saveProfile': 'Save Profile',
    'profile.saving': 'Saving...',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.connectWallet': 'Connect Wallet',
    'profile.connectWalletDesc': 'Please connect wallet to view profile',
    
    // Roadmap
    'roadmap.title': 'Project Roadmap',
    'roadmap.subtitle': 'Our path to success',
    'roadmap.q4_2025': 'Q4 2025',
    'roadmap.launch': 'Platform Launch',
    'roadmap.launchItems': 'Platform launch|Start fundraising|Purchase first cars',
    'roadmap.dec_jan': 'December 2025 - January 2026',
    'roadmap.fundraising': 'Fundraising',
    'roadmap.fundraisingItems': 'Reach ฿2.8M|Fill all 6-7 slots|Activate all vehicles',
    'roadmap.jan_2026': 'January 2026',
    'roadmap.roundClose': 'Round Close',
    'roadmap.roundCloseItems': 'Close fundraising|Company registration|Start operations',
    'roadmap.feb_2026': 'February 2026',
    'roadmap.legal': 'Legal Setup',
    'roadmap.legalItems': 'Legal entity registration|Vehicle registration|Licenses and permits',
    'roadmap.mar_2026': 'March 2026',
    'roadmap.firstPayouts': 'First Payouts',
    'roadmap.firstPayoutsItems': 'Launch rentals|First investor payouts|Operations stabilization',
    'roadmap.jul_2026': 'July 2026',
    'roadmap.expansion': 'Expansion',
    'roadmap.expansionItems': 'Buyout 6-month investments|Fleet expansion|New locations',
    'roadmap.oct_2026': 'October 2026',
    'roadmap.newProducts': 'New Products',
    'roadmap.newProductsItems': 'Launch new services|Hotel partnerships|Brand development',
    'roadmap.2027': '2027',
    'roadmap.continued': 'Continued Growth',
    'roadmap.continuedItems': 'Business scaling|New investment rounds|International expansion',
    'roadmap.disclaimer': 'This is an approximate development plan. Actual timelines may vary depending on market conditions and other factors.',
    
    // Alert
    'alert.connectWallet': 'Please connect wallet to invest',

    // Chat
    'chat.agentName': 'TMC Consultant',
    'chat.consultantOnline': 'Online',
    'chat.typing': 'Typing...',
    'chat.end': 'End',
    'chat.endChat': 'End chat',
    'chat.endChatConfirm': 'Are you sure you want to end the chat?',
    'chat.contactManager': 'Contact manager',
    'chat.waitingForManager': 'Waiting for manager...',
    'chat.startChat': 'Start chat',
    'chat.introduceYourself': 'Please introduce yourself',
    'chat.yourName': 'Your name',
    'chat.namePlaceholder': 'Enter name',
    'chat.emailOptional': 'Email (optional)',
    'chat.welcomeMessage': 'Hello, {name}! How can I help you?',
    'chat.managerRequestSent': 'Manager request sent. Please wait for response.',

    // Dashboard
    'dashboard.myDashboard': 'Investor Dashboard',
    'dashboard.manageInvestments': 'Manage your assets and track your profit',
    'dashboard.invested': 'Total Invested',
    'dashboard.earned': 'Total Earned',
    'dashboard.totalBalance': 'Total Balance',
    'dashboard.active': 'Active Tiers',
    'dashboard.earningsProjection': 'Earnings Projection',
    'dashboard.balanceByMonth': 'Capital growth over time',
    'dashboard.balance': 'Balance',
    'dashboard.monthlyIncome': 'Monthly Income',
    'dashboard.accumulated': 'Accumulated',
    'dashboard.withdraw': 'Withdraw',
    'dashboard.staking': 'Staking',
    'dashboard.carShare': 'Car Share',
    'dashboard.connectWallet': 'Connect Wallet',
    'dashboard.connectToView': 'Please connect your MetaMask to view your investments',
    'dashboard.loading': 'Loading data...',
    'dashboard.noInvestments': 'No investments found',
    'dashboard.startInvestingHere': 'Your investments will appear here after payment',
    'dashboard.withdrawn': 'Withdrawn',
    'dashboard.withdrawalTypeLabel': 'Withdrawal type:',
    'dashboard.withdrawAll': 'All funds',
    'dashboard.withdrawAllDesc': 'Principal + accumulated earnings',
    'dashboard.withdrawEarnings': 'Earnings only',
    'dashboard.withdrawEarningsDesc': 'Accumulated profit, principal remains',
    'dashboard.withdrawPrincipal': 'Principal only',
    'dashboard.withdrawPrincipalDesc': 'Initial investment amount',
    'dashboard.baseAmount': 'Amount:',
    'dashboard.baseFee': 'Base fee (3%):',
    'dashboard.earlyFeeMayApply': '+ early withdrawal fee (5%) if lock period not expired',
    'dashboard.estimatedAmount': 'Estimated amount to receive:',
    'dashboard.withdrawalWallet': 'Withdrawal wallet (optional)',
    'dashboard.withdrawalWalletHint': 'If not specified, connected wallet will be used',
    'dashboard.submitWithdrawal': 'Submit request',
    'dashboard.processing': 'Processing...',
    'dashboard.withdrawalSuccess': 'Request sent!',
    'dashboard.withdrawalSuccessDesc': 'Your withdrawal request will be processed by admin within 48 hours.',
    'dashboard.withdrawalPending': 'Pending approval...',
    'dashboard.walletRequired': 'Please connect wallet or enter withdrawal address',
    'dashboard.invalidWalletFormat': 'Invalid wallet address format',
    'dashboard.withdrawalError': 'Error submitting withdrawal request',
  },
  th: {
    // Header
    'header.home': 'หน้าแรก',
    'header.about': 'เกี่ยวกับ',
    'header.invest': 'ลงทุน',
    'header.dashboard': 'แดชบอร์ด',
    'header.roadmap': 'แผนงาน',
    'header.profile': 'โปรไฟล์',
    'header.connectWallet': 'เชื่อมต่อกระเป๋า',
    'header.disconnect': 'ตัดการเชื่อมต่อ',
    
    // Hero
    'hero.title': 'ลงทุนในธุรกิจให้เช่ารถโตโยต้าในพัทยา',
    'hero.subtitle': 'รายได้แบบพาสซีฟจากการเช่ารถในไทยด้วยการลงทุนคริปโต',
    'hero.invested': 'ลงทุนแล้ว',
    'hero.investors': 'นักลงทุน',
    'hero.cars': 'รถยนต์',
    'hero.investNow': 'ลงทุนตอนนี้',
    
    // Investment Tiers
    'tiers.title': 'ระดับการลงทุน',
    'tiers.subtitle': 'เลือกตัวเลือกการลงทุนของคุณ',
    'tiers.from': 'จาก',
    'tiers.selectTier': 'เลือกระดับ',
    'tiers.connectWallet': 'เชื่อมต่อกระเป๋า',
    
    // About
    'about.title': 'เกี่ยวกับโครงการ',
    'about.subtitle': 'Thailand My Car เป็นแพลตฟอร์มนวัตกรรมสำหรับการลงทุนในธุรกิจให้เช่ารถโตйоต้าในพัทยา',
    'about.cars': 'กองรถ',
    'about.carsSubtitle': 'รถยนต์ภายใต้การจัดการ',
    'about.monthlyIncome': 'รายได้',
    'about.monthlyIncomeSubtitle': 'รายได้ต่อเดือนที่มั่นคง',
    'about.occupancy': 'อัตราการเช่า',
    'about.occupancySubtitle': 'อัตราการเช่าเฉลี่ย',
    'about.location': 'สถานที่',
    'about.locationValue': 'พัทยา',
    'about.locationSubtitle': 'ศูนย์กลางการท่องเที่ยวของไทย',
    'about.growthTitle': 'ประวัติการเติบโต',
    'about.cars3': '3 คัน',
    'about.cars6': '6 คัน',
    'about.cars8': '8 คัน',
    'about.launch': 'เปิดตัวโครงการ',
    'about.growth': 'การขยายตัวอย่างต่อเนื่อง',
    'about.now': 'ระยะปัจจุบัน',
    'about.insurance': 'การประกันภัย',
    'about.insuranceDesc': 'รถยนต์ทุกคันมีประกันภัยชั้นหนึ่งเพื่อการคุ้มครองนักลงทุนสูงสุด',
    'about.transparency': 'ความโปร่งใส',
    'about.transparencyDesc': 'รายงานการเช่าและการจ่ายเงินเต็มรูปแบบผ่านแดชบอร์ดและสมาร์ทคอนแทรค',
    'about.experience': 'ประสบการณ์ทีมงาน',
    'about.experienceDesc': 'ประสบการณ์กว่า 5 ปีในตลาดเช่ารถในไทย รับประกันประสิทธิภาพการจัดการ',
    'about.fleetTitle': 'กองรถของเรา',
    'about.fleetDesc': 'เราใช้เฉพาะรถ Toyota รุ่นที่น่าเชื่อถือและเป็นที่นิยมเพื่อให้มั่นใจในสภาพคล่องสูง',
    'about.velozDesc': 'รถ MPV 7 ที่นั่งระดับพรีเมียม เหมาะสำหรับทริปครอบครัวและกลุ่มใหญ่',
    'about.yarisDesc': 'รถแฮทช์แบ็กขนาดกะทัดรัดและประหยัดน้ำมัน เป็นตัวเลือกที่ยอดเยี่ยมสำหรับการเดินทางในเมือง',
    
    // Footer
    'footer.description': 'ลงทุนในธุรกิจให้เช่ารถในประเทศไทย',
    'footer.contacts': 'ติดต่อ',
    'footer.rights': 'สงวนลิขสิทธิ์',
    'footer.disclaimer': 'การลงทุนมีความเสี่ยง ปรึกษาผู้เชี่ยวชาญ',
    
    // Cookies
    'cookies.message': 'เราใช้คุกกี้เพื่อปรับปรุงประสบการณ์ของคุณบนเว็บไซต์ของเรา',
    'cookies.accept': 'ยอมรับ',
    'cookies.decline': 'ปฏิเสธ',
    
    // Profile
    'profile.back': 'กลับ',
    'profile.yourProfile': 'โปรไฟล์ของคุณ',
    'profile.memberSince': 'สมาชิกตั้งแต่',
    'profile.totalInvested': 'ลงทุนทั้งหมด',
    'profile.investments': 'การลงทุน',
    'profile.activeInvestments': 'ที่ใช้งานอยู่',
    'profile.inBaht': 'เป็นบาท',
    'profile.personalInfo': 'ข้อมูลส่วนตัว',
    'profile.name': 'ชื่อ',
    'profile.namePlaceholder': 'ชื่อของคุณ',
    'profile.bio': 'ประวัติ',
    'profile.bioPlaceholder': 'บอกเล่าเกี่ยวกับตัวคุณ...',
    'profile.saveProfile': 'บันทึกโปรไฟล์',
    'profile.saving': 'กำลังบันทึก...',
    'profile.updateSuccess': 'อัพเดทโปรไฟล์สำเร็จ',
    'profile.connectWallet': 'เชื่อมต่อกระเป๋า',
    'profile.connectWalletDesc': 'กรุณาเชื่อมต่อกระเป๋าเพื่อดูโปรไฟล์',
    
    // Roadmap
    'roadmap.title': 'แผนงานโครงการ',
    'roadmap.subtitle': 'เส้นทางสู่ความสำเร็จของเรา',
    'roadmap.q4_2025': 'ไตรมาส 4 2568',
    'roadmap.launch': 'เปิดตัวแพลตฟอร์ม',
    'roadmap.launchItems': 'เปิดตัวแพลตฟอร์ม|เริ่มระดมทุน|ซื้อรถคันแรก',
    'roadmap.dec_jan': 'ธันวาคม 2568 - มกราคม 2569',
    'roadmap.fundraising': 'ระดมทุน',
    'roadmap.fundraisingItems': 'บรรลุเป้า ฿2.8M|เติมเต็มทุกช่อง 6-7|เปิดใช้งานรถทั้งหมด',
    'roadmap.jan_2026': 'มกราคม 2569',
    'roadmap.roundClose': 'ปิดรอบ',
    'roadmap.roundCloseItems': 'ปิดการระดมทุน|จดทะเบียนบริษัท|เริ่มดำเนินงาน',
    'roadmap.feb_2026': 'กุมภาพันธ์ 2569',
    'roadmap.legal': 'จัดการด้านกฎหมาย',
    'roadmap.legalItems': 'จดทะเบียนนิติบุคคล|จดทะเบียนรถยนต์|ใบอนุญาต',
    'roadmap.mar_2026': 'มีนาคม 2569',
    'roadmap.firstPayouts': 'จ่ายเงินครั้งแรก',
    'roadmap.firstPayoutsItems': 'เริ่มให้เช่า|จ่ายเงินนักลงทุนครั้งแรก|ทำให้ดำเนินงานมั่นคง',
    'roadmap.jul_2026': 'กรกฎาคม 2569',
    'roadmap.expansion': 'ขยายธุรกิจ',
    'roadmap.expansionItems': 'ซื้อคืนการลงทุน 6 เดือน|ขยายกองรถ|สถานที่ใหม่',
    'roadmap.oct_2026': 'ตุลาคม 2569',
    'roadmap.newProducts': 'ผลิตภัณฑ์ใหม่',
    'roadmap.newProductsItems': 'เปิดบริการใหม่|พันธมิตรโรงแรม|พัฒนาแบรนด์',
    'roadmap.2027': '2570',
    'roadmap.continued': 'เติบโตต่อเนื่อง',
    'roadmap.continuedItems': 'ขยายธุรกิจ|รอบลงทุนใหม่|ขยายต่างประเทศ',
    'roadmap.disclaimer': 'นี่คือแผนการพัฒนาโดยประมาณ ระยะเวลาจริงอาจแตกต่างไปตามสภาพตลาดและปัจจัยอื่นๆ',
    
    // Alert
    'alert.connectWallet': 'กรุณาเชื่อมต่อกระเป๋าเพื่อลงทุน',

    // Chat
    'chat.agentName': 'ที่ปรึกษา TMC',
    'chat.consultantOnline': 'ออนไลน์',
    'chat.typing': 'กำลังพิมพ์...',
    'chat.end': 'จบ',
    'chat.endChat': 'จบแชท',
    'chat.endChatConfirm': 'คุณแน่ใจหรือไม่ว่าต้องการจบแชท?',
    'chat.contactManager': 'ติดต่อผู้จัดการ',
    'chat.waitingForManager': 'รอผู้จัดการ...',
    'chat.startChat': 'เริ่มแชท',
    'chat.introduceYourself': 'กรุณาแนะนำตัวเอง',
    'chat.yourName': 'ชื่อของคุณ',
    'chat.namePlaceholder': 'ใส่ชื่อ',
    'chat.emailOptional': 'อีเมล (ไม่บังคับ)',
    'chat.welcomeMessage': 'สวัสดี {name}! ฉันช่วยอะไรได้บ้าง?',
    'chat.managerRequestSent': 'ส่งคำขอผู้จัดการแล้ว กรุณารอการตอบกลับ',

    // Dashboard
    'dashboard.myDashboard': 'แผงควบคุมนักลงทุน',
    'dashboard.manageInvestments': 'จัดการสินทรัพย์และติดตามกำไรของคุณ',
    'dashboard.invested': 'ลงทุนทั้งหมด',
    'dashboard.earned': 'รายได้ทั้งหมด',
    'dashboard.totalBalance': 'ยอดคงเหลือทั้งหมด',
    'dashboard.active': 'การลงทุนที่ใช้งานอยู่',
    'dashboard.earningsProjection': 'ประมาณการรายได้',
    'dashboard.balanceByMonth': 'การเติบโตของทุนเมื่อเวลาผ่านไป',
    'dashboard.balance': 'ยอดคงเหลือ',
    'dashboard.monthlyIncome': 'รายได้ต่อเดือน',
    'dashboard.accumulated': 'สะสมแล้ว',
    'dashboard.withdraw': 'ถอนเงิน',
    'dashboard.staking': 'การสเตกกิ้ง',
    'dashboard.carShare': 'ส่วนแบ่งรถยนต์',
    'dashboard.connectWallet': 'เชื่อมต่อกระเป๋า',
    'dashboard.connectToView': 'กรุณาเชื่อมต่อ MetaMask เพื่อดูการลงทุนของคุณ',
    'dashboard.loading': 'กำลังโหลดข้อมูล...', 
    'dashboard.noInvestments': 'ไม่พบการลงทุน',
    'dashboard.startInvestingHere': 'การลงทุนของคุณจะปรากฏที่นี่หลังจากการชำระเงิน',
    'dashboard.withdrawn': 'ถอนแล้ว',
    'dashboard.withdrawalTypeLabel': 'ประเภทการถอน:',
    'dashboard.withdrawAll': 'เงินทั้งหมด',
    'dashboard.withdrawAllDesc': 'เงินต้น + ผลตอบแทนสะสม',
    'dashboard.withdrawEarnings': 'ผลตอบแทนเท่านั้น',
    'dashboard.withdrawEarningsDesc': 'กำไรสะสม เงินต้นยังคงอยู่',
    'dashboard.withdrawPrincipal': 'เงินต้นเท่านั้น',
    'dashboard.withdrawPrincipalDesc': 'จำนวนเงินลงทุนเริ่มต้น',
    'dashboard.baseAmount': 'จำนวนเงิน:',
    'dashboard.baseFee': 'ค่าธรรมเนียมพื้นฐาน (3%):',
    'dashboard.earlyFeeMayApply': '+ ค่าธรรมเนียมถอนก่อนกำหนด (5%) หากยังไม่ครบกำหนด',
    'dashboard.estimatedAmount': 'จำนวนเงินโดยประมาณที่จะได้รับ:',
    'dashboard.withdrawalWallet': 'กระเป๋าเงินสำหรับถอน (ไม่บังคับ)',
    'dashboard.withdrawalWalletHint': 'หากไม่ระบุ จะใช้กระเป๋าเงินที่เชื่อมต่ออยู่',
    'dashboard.submitWithdrawal': 'ส่งคำขอ',
    'dashboard.processing': 'กำลังดำเนินการ...',
    'dashboard.withdrawalSuccess': 'ส่งคำขอแล้ว!',
    'dashboard.withdrawalSuccessDesc': 'คำขอถอนเงินของคุณจะได้รับการพิจารณาโดยผู้ดูแลภายใน 48 ชั่วโมง',
    'dashboard.withdrawalPending': 'รอการอนุมัติ...',
    'dashboard.walletRequired': 'โปรดเชื่อมต่อกระเป๋าเงินหรือใส่ที่อยู่สำหรับถอน',
    'dashboard.invalidWalletFormat': 'รูปแบบที่อยู่กระเป๋าเงินไม่ถูกต้อง',
    'dashboard.withdrawalError': 'เกิดข้อผิดพลาดในการส่งคำขอถอนเงิน',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ru');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['ru', 'en', 'th'].includes(savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
