import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ru' | 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

/**
 * Translations for Thailand My Car
 * Professional English translations for investment platform
 */
const translations: Record<Language, Record<string, string>> = {
  ru: {
    // === Navigation ===
    'nav.home': 'Главная',
    'nav.about': 'О проекте',
    'nav.invest': 'Инвестиции',
    'nav.dashboard': 'Dashboard',
    'nav.roadmap': 'Roadmap',
    'nav.profile': 'Профиль',

    // === Header ===
    'header.slogan': 'Инвестиции в рентал',
    'header.connect': 'Connect',
    'header.signing': 'Подписание...',
    'header.disconnect': 'Отключить',
    'header.connectWallet': 'Подключить кошелек',
    'header.language': 'Язык',

    // === Hero Section ===
    'hero.badge': 'Инвестиции в рентал-бизнес через блокчейн',
    'hero.title': 'Инвестируйте',
    'hero.titleAccent': 'в рентал-бизнес',
    'hero.titleCrypto': 'с криптовалютой',
    'hero.subtitle': '{count} автомобилей Toyota • От $1,000 • 2.5%/мес или авто в собственность',
    'hero.description': 'Станьте совладельцем автопарка Toyota в Паттайе. Стабильный доход от аренды туристам.',
    'hero.cta': 'Инвестировать сейчас',
    'hero.learnMore': 'Узнать больше',
    'hero.target': 'Цель сбора',
    'hero.collected': 'собрано',
    'hero.investors': 'Инвесторов',
    'hero.daysLeft': 'дней осталось',
    'hero.carsAvailable': 'Авто доступно',
    'hero.of': 'из',
    'hero.progress': 'Прогресс сбора',
    'hero.staking': 'Стейкинг',
    'hero.stakingRate': '2.5%/мес',
    'hero.bigInvestors': 'Крупным инвесторам',
    'hero.bigInvestorsReturn': '+20% или авто',
    'hero.fundraising': 'Сбор средств',
    'hero.goal': 'Цель',
    'hero.carOwnership': 'Авто в собственность',
    'hero.available': 'свободно',
    'hero.minStaking': 'Min: $1,000 (стейкинг)',
    'hero.minCar': '$12,400 (авто)',

    // === About Project ===
    'about.title': 'О проекте',
    'about.subtitle': 'Действующий бизнес по прокату автомобилей Toyota в Паттайе с проверенными показателями доходности',
    'about.cars': 'Автомобилей',
    'about.carsSubtitle': 'Toyota в автопарке',
    'about.monthlyIncome': 'Ежемесячный доход',
    'about.monthlyIncomeSubtitle': '฿ стабильный поток',
    'about.occupancy': 'Загрузка',
    'about.occupancySubtitle': 'Средняя за 2024',
    'about.location': 'Локация',
    'about.locationValue': 'Паттайя',
    'about.locationSubtitle': 'Туристический центр',
    'about.launch': 'Запуск',
    'about.growth': 'Рост',
    'about.now': 'Сейчас',
    'about.cars3': '3 авто',
    'about.cars6': '6 авто',
    'about.cars9': '9 авто',
    'about.growthTitle': 'История роста компании',
    'about.insurance': 'Страхование',
    'about.insuranceDesc': 'Полная страховка Type 1 (ชั้น 1) на авто и пассажиров',
    'about.insuranceCoverage1': 'Полное покрытие ущерба автомобиля',
    'about.insuranceCoverage2': 'Угон и злоумышленные действия',
    'about.insuranceCoverage3': 'Стихийные бедствия (наводнение, пожар)',
    'about.insuranceCoverage4': 'Медицинские расходы водителя и пассажиров',
    'about.insuranceCoverage5': 'Ответственность перед третьими лицами',
    'about.insuranceCoverage6': 'Эвакуация и помощь на дороге 24/7',
    'about.transparency': 'Прозрачность',
    'about.transparencyDesc': 'Ежемесячные отчеты и доступ к метрикам в реальном времени',
    'about.experience': 'Опыт',
    'about.experienceDesc': '2+ года успешной работы на рынке рентала в Таиланде',
    'about.fleetTitle': 'Наш автопарк Toyota',
    'about.fleetDesc': 'Премиальные автомобили Toyota в отличном состоянии на живописных дорогах Таиланда',
    'about.velozDesc': 'Premium 7-seater • Идеально для семьи',
    'about.yarisDesc': 'Компактный седан • Экономичный и надёжный',

    // === Investment Tiers ===
    'tiers.title': 'Варианты участия',
    'tiers.subtitle': 'Выберите подходящий вариант партнёрского займа',
    'tiers.minInvestment': 'Минимальная инвестиция',
    'tiers.fullCost': 'Полная стоимость автомобиля',
    'tiers.expectedReturn': 'Ожидаемая доходность (прогноз)',
    'tiers.after6months': 'Через 6 месяцев',
    'tiers.connectWallet': 'Подключите кошелек',
    'tiers.allReserved': 'Все авто зарезервированы',
    'tiers.invest': 'Инвестировать',
    'tiers.perYear': 'годовых',
    'tiers.perMonth': '/мес',
    'tiers.upTo': 'до',
    'tiers.carsLeft': 'авто осталось',
    'tiers.partnerChoice': 'Выбор партнёра:',
    'tiers.takeReturn': 'Забрать',
    'tiers.return': 'возврат',
    'tiers.or': 'ИЛИ',
    'tiers.waitCar': 'Ждать',
    'tiers.carOwnership': 'авто в собственность',
    'tiers.afterLoan': '(после выплаты кредита)',
    'tiers.withdrawAnytime': 'Вывод в любой момент',
    'tiers.feeUntil6mo': 'комиссия до 6 мес',
    'tiers.fewCarsLeft': 'Осталось мало авто! Кто первый - тот получает.',
    'tiers.walletInfo': 'Кошелёк для инвестиций (BSC Network):',
    'tiers.acceptedTokens': 'Принимаем: USDT, USDC на Binance Smart Chain (BSC)',
    'tiers.networkFee': 'Комиссия сети: ~$0.20',
    // Tier names and descriptions from database
    'tiers.tierName.staking': 'Стейкинг',
    'tiers.tierName.carShare': 'Доля в автомобиле',
    'tiers.tierDesc.staking': 'Пассивный доход с гибкими условиями вывода',
    'tiers.tierDesc.carShare': 'Получите автомобиль в собственность или гарантированный возврат',
    // Features from database
    'tiers.feature.monthlyRate': '2.5% в месяц (30% годовых)',
    'tiers.feature.withdrawAnytime': 'Вывод в любой момент',
    'tiers.feature.earlyFee': '5% комиссия при выводе до 6 мес',
    'tiers.feature.monthlyAccrual': 'Ежемесячное начисление процентов',
    'tiers.feature.sixMonthChoice': 'Через 6 мес: +20% возврат ИЛИ ждать авто',
    'tiers.feature.carOwnership': 'Автомобиль в собственность после выплаты кредита',
    'tiers.feature.priority': 'Приоритет: кто первый - тот получает авто',
    'tiers.feature.changeChoice': 'Можно изменить выбор до закрытия кредита',

    // === Invest Modal ===
    'modal.title': 'Инвестирование',
    'modal.step': 'Шаг',
    'modal.of': 'из',
    'modal.agreement': 'Соглашение о партнёрском займе',
    'modal.scrollToEnd': 'Прокрутите до конца',
    'modal.agreeTerms': 'Я прочитал и принимаю условия',
    'modal.readAgreement': 'Прочитайте соглашение',
    'modal.continue': 'Продолжить',
    'modal.amount': 'Сумма инвестиции',
    'modal.minAmount': 'Минимум',
    'modal.maxAmount': 'Максимум',
    'modal.expectedReturn': 'Ожидаемый доход (прогноз)',
    'modal.expectedReturnCar': 'Ожидаемый возврат до +20%',
    'modal.payViaWallet': 'Оплатить через кошелек',
    'modal.confirmInWallet': 'Подтвердите в кошельке...',
    'modal.paymentDetails': 'Оплата по реквизитам',
    'modal.comingSoon': 'coming soon',
    'modal.awaitingPayment': 'Ожидает перевода',
    'modal.awaitingVerification': 'Ожидает проверки',
    'modal.back': 'Назад',
    'modal.close': 'Закрыть',
    'modal.enterTxHash': 'Введите TX Hash',
    'modal.invalidTxHash': 'Неверный формат TX Hash',
    'modal.errorCreating': 'Ошибка создания инвестиции',
    'modal.scrollDown': 'Прокрутите вниз',
    'modal.next': 'Далее',
    'modal.backToAgreement': '← Назад к соглашению',
    'modal.choosePayment': 'Выберите способ оплаты',
    'modal.testnetMode': '⚠️ TESTNET MODE - Тестовая сеть BSC',
    'modal.or': 'или',
    'modal.orCarOwnership': 'или авто в собственность',
    'modal.applicationCreated': 'Заявка создана!',
    'modal.investmentPending': 'Инвестиция на рассмотрении',
    'modal.amountLabel': 'Сумма:',
    'modal.statusLabel': 'Статус:',
    'modal.willCheck24h': 'Проверим транзакцию в течение 24 часов',
    'modal.done': 'Готово',
    'modal.minError': 'Минимум: ${amount}',
    'modal.maxError': 'Для ${amount}+ выберите "Доля в автомобиле"',
    // Agreement text
    'modal.agreementTitle': 'СОГЛАШЕНИЕ О ПАРТНЁРСКОМ ЗАЙМЕ',
    'modal.agreementIntro': 'Договор частного займа между физическими лицами согласно Гражданскому и Торговому кодексу Таиланда.',
    'modal.agreementNature': '1. Характер сделки:',
    'modal.agreementNatureText': 'Частный займ между знакомыми лицами для развития бизнеса по аренде автомобилей.',
    'modal.agreementNotPublic': 'НЕ является публичным предложением ценных бумаг',
    'modal.agreementRisks': '2. РИСКИ:',
    'modal.agreementRisksText': 'Доходность —',
    'modal.agreementNotGuaranteed': 'ПРОГНОЗ, НЕ ГАРАНТИРУЕТСЯ',
    'modal.agreementRisksNote': 'Компания владеет реальными активами и имеет страховое покрытие, что минимизирует риски.',
    'modal.agreementReturn': '3. Возврат:',
    'modal.agreementReturnText': 'Досрочный возврат возможен с удержанием компенсации.',
    'modal.agreementTaxes': '4. Налоги:',
    'modal.agreementTaxesText': 'Ответственность каждой стороны по законам своей страны.',
    'modal.agreementDisputes': '5. Споры:',
    'modal.agreementDisputesText': 'Разрешаются по тайскому праву.',
    'modal.agreementAge': '6. Возраст:',
    'modal.agreementAgeText': 'Участник подтверждает достижение',
    'modal.agreementAgeYears': '20 лет',
    'modal.agreementData': '7. Данные:',
    'modal.agreementDataText': 'Согласие на обработку согласно PDPA Таиланда.',
    'modal.agreementRoadmap': '8. Roadmap:',
    'modal.agreementRoadmapText': 'План развития носит ориентировочный характер. Сроки и этапы могут корректироваться в зависимости от рыночных условий и бизнес-возможностей.',
    'modal.agreementVersion': 'Версия 1.1 • 08.12.2025 • Thailand My Car, Pattaya',

    // === Investor Dashboard ===
    'dashboard.title': 'Панель инвестора',
    'dashboard.totalInvested': 'Всего инвестировано',
    'dashboard.totalEarned': 'Заработано',
    'dashboard.activeInvestments': 'Активных инвестиций',
    'dashboard.pendingPayouts': 'Ожидает выплаты',
    'dashboard.yourInvestments': 'Ваши инвестиции',
    'dashboard.noInvestments': 'У вас пока нет инвестиций',
    'dashboard.startInvesting': 'Начните инвестировать, чтобы видеть статистику',
    'dashboard.carShare': 'Доля в авто',
    'dashboard.staking': 'Стейкинг',
    'dashboard.invested': 'Инвестировано',
    'dashboard.earned': 'Заработано',
    'dashboard.status': 'Статус',
    'dashboard.withdraw': 'Вывести',
    'dashboard.withdrawalRequest': 'Запрос на вывод',
    'dashboard.withdrawalType': 'Тип вывода',
    'dashboard.earningsOnly': 'Только проценты',
    'dashboard.principalOnly': 'Только тело депозита',
    'dashboard.withdrawAll': 'Всё (тело + проценты)',
    'dashboard.walletAddress': 'Адрес кошелька BEP20',
    'dashboard.enterWallet': 'Введите адрес кошелька',
    'dashboard.invalidWallet': 'Неверный формат адреса. Адрес BEP20 должен начинаться с 0x и содержать 42 символа',
    'dashboard.submitRequest': 'Отправить запрос',
    'dashboard.cancel': 'Отмена',
    'dashboard.noConnection': 'Нет подключения к серверу. Проверьте интернет-соединение.',
    'dashboard.loadError': 'Произошла ошибка при загрузке данных. Попробуйте позже.',
    'dashboard.networkError': 'Ошибка сети. Попробуйте позже.',
    'dashboard.myDashboard': 'Мой Dashboard',
    'dashboard.manageInvestments': 'Управляйте своими инвестициями',
    'dashboard.loading': 'Загрузка инвестиций...',
    'dashboard.loadingError': 'Ошибка загрузки',
    'dashboard.retry': 'Повторить',
    'dashboard.connectWallet': 'Подключите кошелек',
    'dashboard.connectToView': 'Для просмотра инвестиций подключите кошелек в меню',
    'dashboard.startInvestingHere': 'Начните инвестировать и следите за доходностью прямо здесь',
    'dashboard.totalBalance': 'Общий баланс',
    'dashboard.active': 'Активных',
    'dashboard.withdrawn': 'Выведено',
    'dashboard.earningsProjection': 'Прогноз доходности',
    'dashboard.balanceByMonth': 'Накопленный баланс по месяцам',
    'dashboard.balance': 'Баланс',
    'dashboard.monthlyIncome': 'Доход/мес',
    'dashboard.date': 'Дата',
    'dashboard.accumulated': 'Накоплено',
    'dashboard.withdrawnPercent': 'Выведено %',
    'dashboard.rate': 'Ставка',
    'dashboard.locked': 'Заблокировано',
    'dashboard.available': 'Доступно',
    'dashboard.untilUnlock': 'До разблокировки',
    'dashboard.days': 'дн.',
    'dashboard.months': 'мес.',
    'dashboard.of': 'из',
    'dashboard.availableForWithdraw': 'Доступно для вывода',
    'dashboard.toWithdraw': 'К выводу',
    'dashboard.statusActive': 'Активна',
    'dashboard.statusPending': 'Ожидает оплаты',
    'dashboard.statusPendingConfirmation': 'Ожидает подтверждения',
    'dashboard.statusWithdrawalRequest': 'Запрос на вывод',
    'dashboard.statusCompleted': 'Завершена',
    'dashboard.selectWithdrawalType': 'Выберите тип вывода',
    'dashboard.walletAddressStep': 'Адрес кошелька',
    'dashboard.confirmation': 'Подтверждение',
    'dashboard.requestSent': 'Заявка отправлена',
    'dashboard.principalStays': 'Тело депозита остаётся и продолжает работать',
    'dashboard.earningsStay': 'Проценты остаются на счёте',
    'dashboard.feePercent': '(комиссия 5%)',
    'dashboard.closeInvestment': 'Всё (закрыть инвестицию)',
    'dashboard.bodyPlusEarnings': 'Тело + проценты',
    'dashboard.earlyWithdrawal': 'Досрочный вывод.',
    'dashboard.earlyWithdrawalNote': 'При выводе тела депозита до окончания срока взимается комиссия 5%. Вывод только процентов — без комиссии.',
    'dashboard.next': 'Далее',
    'dashboard.walletAddressLabel': 'Адрес кошелька USDT (BEP20 / BSC)',
    'dashboard.important': 'Важно!',
    'dashboard.bep20Warning': 'Убедитесь, что адрес поддерживает сеть BEP20 (BSC)',
    'dashboard.wrongAddressWarning': 'Отправка на неправильный адрес приведёт к потере средств',
    'dashboard.checkAddress': 'Проверьте адрес несколько раз',
    'dashboard.back': 'Назад',
    'dashboard.verify': 'Проверить',
    'dashboard.addressForReceiving': 'Адрес для получения USDT:',
    'dashboard.confirmAddress': 'Я подтверждаю, что адрес кошелька верный и поддерживает сеть BEP20 (BSC). Понимаю, что ошибка приведёт к потере средств.',
    'dashboard.totalToWithdraw': 'Итого к выводу:',
    'dashboard.platformFee': 'Комиссия платформы (3%)',
    'dashboard.earlyWithdrawalFee': 'Комиссия за ранний вывод (+5%)',
    'dashboard.youWillReceive': 'Вы получите:',
    'dashboard.processingTime': 'Сроки обработки',
    'dashboard.processingUp48h': 'Обработка заявки: до 48 часов',
    'dashboard.payoutsWeekdays': 'Выплаты в будние дни (Пн-Пт)',
    'dashboard.changeAddress': 'Изменить адрес',
    'dashboard.sending': 'Отправка...',
    'dashboard.sendRequest': 'Отправить заявку',
    'dashboard.requestAccepted': 'Заявка принята!',
    'dashboard.withdrawalSent': 'Ваша заявка на вывод отправлена на обработку',
    'dashboard.receivingAddress': 'Адрес получения:',
    'dashboard.expectTransfer48h': 'Ожидайте перевод в течение 48 часов.',
    'dashboard.adminMayContact': 'Администратор может связаться с вами для подтверждения.',
    'dashboard.close': 'Закрыть',
    'dashboard.principal': 'Тело депозита:',
    'dashboard.accumulatedEarnings': 'Накопленные проценты:',
    'dashboard.months_short': 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec',
    'dashboard.months_short_ru': 'Янв|Фев|Мар|Апр|Май|Июн|Июл|Авг|Сен|Окт|Ноя|Дек',

    // === Profile Page ===
    'profile.title': 'Ваш профиль',
    'profile.yourProfile': 'Ваш профиль',
    'profile.wallet': 'Кошелек',
    'profile.name': 'Имя',
    'profile.email': 'Email',
    'profile.phone': 'Телефон',
    'profile.save': 'Сохранить',
    'profile.withdrawRequest': 'Запрос на вывод',
    'profile.withdrawSent': 'Запрос на вывод отправлен! Администратор свяжется с вами.',
    'profile.withdrawError': 'Ошибка при отправке запроса',
    'profile.status.pending': 'Ожидает',
    'profile.status.pending_confirmation': 'На проверке',
    'profile.status.active': 'Активна',
    'profile.status.withdrawal_requested': 'Запрос на вывод',
    'profile.status.completed': 'Завершена',
    'profile.status.cancelled': 'Отменена',
    'profile.back': 'Назад',
    'profile.memberSince': 'Участник с',
    'profile.totalInvested': 'Инвестировано',
    'profile.investments': 'Инвестиций',
    'profile.activeInvestments': 'Активных',
    'profile.inBaht': 'В батах',
    'profile.personalInfo': 'Личная информация',
    'profile.namePlaceholder': 'Введите ваше имя',
    'profile.bio': 'О себе',
    'profile.bioPlaceholder': 'Расскажите о себе...',
    'profile.saving': 'Сохранение...',
    'profile.saveProfile': 'Сохранить профиль',
    'profile.updateSuccess': 'Профиль успешно обновлён!',
    'profile.withdrawalSent': 'Запрос на вывод отправлен! Администратор свяжется с вами.',
    'profile.withdrawalError': 'Ошибка при отправке запроса',
    'profile.connectWallet': 'Подключите кошелёк',
    'profile.connectWalletDesc': 'Для просмотра профиля подключите кошелёк',
    'profile.statusPending': 'Ожидает',
    'profile.statusPendingConfirm': 'На проверке',
    'profile.statusActive': 'Активна',
    'profile.statusWithdrawalRequested': 'Запрос на вывод',
    'profile.statusCompleted': 'Завершена',
    'profile.statusCancelled': 'Отменена',
    'profile.sessionExpiredTitle': '⏱️ Сессия истекла',
    'profile.sessionExpiredDesc': 'Ваша сессия авторизации истекла. Пожалуйста, переподключите кошелёк:',
    'profile.sessionExpiredStep1': 'Нажмите на кнопку кошелька в правом верхнем углу',
    'profile.sessionExpiredStep2': 'Отключите текущий кошелёк',
    'profile.sessionExpiredStep3': 'Подключите кошелёк заново',
    'profile.walletNotConnectedTitle': '🔗 Кошелёк не подключён',
    'profile.walletNotConnectedDesc': 'Для просмотра профиля необходимо подключить кошелёк. Нажмите на кнопку "Подключить кошелёк" в правом верхнем углу.',
    'profile.loadFailedTitle': '❌ Ошибка загрузки',
    'profile.loadFailedDesc': 'Не удалось загрузить данные профиля. Попробуйте обновить страницу или переподключить кошелёк.',

    // === Roadmap ===
    'roadmap.title': 'Roadmap',
    'roadmap.subtitle': 'План развития проекта',
    'roadmap.q4_2025': 'Q4 2025',
    'roadmap.launch': 'Запуск платформы',
    'roadmap.launchItems': 'Создание Web3 платформы|Подключение MetaMask|Дизайн и UI/UX',
    'roadmap.dec_jan': 'Декабрь 2025 - Январь 2026',
    'roadmap.fundraising': 'Сбор средств',
    'roadmap.fundraisingItems': 'Привлечение инвесторов|Достижение цели ฿2.8M|KYC и AML процедуры',
    'roadmap.jan_2026': 'Январь 2026',
    'roadmap.roundClose': 'Закрытие раунда',
    'roadmap.roundCloseItems': 'Завершение сбора средств|Начало юридического оформления',
    'roadmap.feb_2026': 'Февраль 2026',
    'roadmap.legal': 'Юридическое оформление',
    'roadmap.legalItems': 'Регистрация долей|Подписание договоров|Настройка автоматических выплат',
    'roadmap.mar_2026': 'Март 2026',
    'roadmap.firstPayouts': 'Первые выплаты',
    'roadmap.firstPayoutsItems': 'Начало ежемесячных выплат|Dashboard с реальными данными|Governance голосования',
    'roadmap.jul_2026': 'Июль 2026',
    'roadmap.expansion': 'Расширение автопарка',
    'roadmap.expansionItems': 'Увеличение парка до 15 автомобилей|Банковское финансирование в Таиланде|Масштабирование операций',
    'roadmap.oct_2026': 'Октябрь 2026',
    'roadmap.newProducts': 'Новые продукты',
    'roadmap.newProductsItems': 'Запуск лизинга под 20% годовых|Открытие филиала на Пхукете|Расширение географии бизнеса',
    'roadmap.2027': '2027',
    'roadmap.continued': 'To be continued...',
    'roadmap.continuedItems': 'Дальнейшее развитие|Новые направления|Международная экспансия',
    'roadmap.disclaimer': 'Roadmap носит ориентировочный характер. Сроки и этапы могут корректироваться в зависимости от рыночных условий, регуляторных требований и бизнес-возможностей. Компания оставляет за собой право вносить изменения для достижения наилучших результатов.',

    // === Footer ===
    'footer.rights': 'Все права защищены',
    'footer.email': 'Email',
    'footer.youtube': 'YouTube',
    'footer.telegram': 'Telegram',
    'footer.contacts': 'Контакты',
    'footer.description': 'Инвестиции в рентал-бизнес автомобилей через блокчейн технологии',
    'footer.disclaimer': 'Частные займы несут риски. Доходность не гарантируется. Это не публичное предложение ценных бумаг. Платформа предназначена для частных договорённостей между знакомыми лицами.',

    // === Chat Widget ===
    'chat.title': 'Поддержка',
    'chat.placeholder': 'Напишите сообщение...',
    'chat.send': 'Отправить',
    'chat.greeting': 'Здравствуйте! Чем могу помочь?',
    'chat.agentName': 'Мира',
    'chat.typing': 'Печатает...',
    'chat.consultantOnline': 'Консультант • Онлайн 24/7',
    'chat.endChatConfirm': 'Завершить чат? История будет удалена.',
    'chat.endChat': 'Завершить чат',
    'chat.end': 'Завершить',
    'chat.startChat': 'Начать чат',
    'chat.introduceYourself': 'Представьтесь, чтобы мы могли помочь вам лучше',
    'chat.yourName': 'Ваше имя',
    'chat.namePlaceholder': 'Как к вам обращаться?',
    'chat.emailOptional': 'Email (опционально)',
    'chat.contactManager': 'Связаться с менеджером',
    'chat.waitingForManager': '⏳ Ожидание менеджера...',
    'chat.writeToManager': 'Напишите менеджеру...',
    'chat.writeMessage': 'Напишите сообщение...',
    'chat.managerRequestSent': '🎧 Запрос отправлен! Менеджер скоро подключится к чату. Пожалуйста, подождите...',
    'chat.welcomeMessage': 'Здравствуйте, {name}! 👋\n\nМеня зовут Мира, я помощник Thailand My Car.\n\nС радостью отвечу на ваши вопросы об инвестициях, доходности, криптоплатежах и нашем автопарке!\n\nЕсли хотите связаться с менеджером - нажмите кнопку 🎧 внизу.\n\nЧем могу помочь? 😊',

    // === Common ===
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.confirm': 'Подтвердить',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.close': 'Закрыть',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.or': 'или',
    'common.and': 'и',

    // === Months ===
    'month.jan': 'Янв',
    'month.feb': 'Фев',
    'month.mar': 'Мар',
    'month.apr': 'Апр',
    'month.may': 'Май',
    'month.jun': 'Июн',
    'month.jul': 'Июл',
    'month.aug': 'Авг',
    'month.sep': 'Сен',
    'month.oct': 'Окт',
    'month.nov': 'Ноя',
    'month.dec': 'Дек',

    // === Alerts ===
    'alert.connectWallet': 'Пожалуйста, подключите кошелек для инвестирования',

    // === Cookies ===
    'cookies.message': 'Мы используем cookies для работы сайта и сохранения ваших настроек.',
    'cookies.accept': 'Принять',
    'cookies.decline': 'Отклонить',

    // === Mobile Wallet Helper ===
    'mobileHelper.title': 'Подключение с телефона',
    'mobileHelper.subtitle': 'Выберите способ подключения',
    'mobileHelper.recommend': 'Рекомендуем: откройте в браузере кошелька',
    'mobileHelper.copyLink': 'Скопируйте ссылку и откройте в браузере кошелька:',
    'mobileHelper.noWallet': 'Нет крипто-кошелька? Войдите по Email:',
    'mobileHelper.loginEmail': 'Войти по Email / Google',
    'mobileHelper.tryWalletConnect': 'Попробовать WalletConnect',
    'mobileHelper.walletConnectNote': 'WalletConnect может работать медленно на некоторых устройствах',
    'mobileHelper.or': 'или',
  },

  en: {
    // === Navigation ===
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.invest': 'Invest',
    'nav.dashboard': 'Dashboard',
    'nav.roadmap': 'Roadmap',
    'nav.profile': 'Profile',

    // === Header ===
    'header.slogan': 'Car Rental Investment',
    'header.connect': 'Connect',
    'header.signing': 'Signing...',
    'header.disconnect': 'Disconnect',
    'header.connectWallet': 'Connect Wallet',
    'header.language': 'Language',

    // === Hero Section ===
    'hero.badge': 'Blockchain-powered car rental investment',
    'hero.title': 'Invest in',
    'hero.titleAccent': 'Car Rental Business',
    'hero.titleCrypto': 'with Cryptocurrency',
    'hero.subtitle': '{count} Toyota vehicles • From $1,000 • 2.5%/mo or car ownership',
    'hero.description': 'Become a co-owner of a Toyota fleet in Pattaya. Stable income from tourist rentals.',
    'hero.cta': 'Invest Now',
    'hero.learnMore': 'Learn More',
    'hero.target': 'Fundraising Goal',
    'hero.collected': 'raised',
    'hero.investors': 'Investors',
    'hero.daysLeft': 'days left',
    'hero.carsAvailable': 'Cars available',
    'hero.of': 'of',
    'hero.progress': 'Funding Progress',
    'hero.staking': 'Staking',
    'hero.stakingRate': '2.5%/mo',
    'hero.bigInvestors': 'Major investors',
    'hero.bigInvestorsReturn': '+20% or vehicle',
    'hero.fundraising': 'Fundraising',
    'hero.goal': 'Goal',
    'hero.carOwnership': 'Car ownership',
    'hero.available': 'available',
    'hero.minStaking': 'Min: $1,000 (staking)',
    'hero.minCar': '$12,400 (car)',

    // === About Project ===
    'about.title': 'About Project',
    'about.subtitle': 'Operating Toyota car rental business in Pattaya with proven profitability',
    'about.cars': 'Vehicles',
    'about.carsSubtitle': 'Toyota fleet',
    'about.monthlyIncome': 'Monthly Income',
    'about.monthlyIncomeSubtitle': '฿ stable cash flow',
    'about.occupancy': 'Occupancy',
    'about.occupancySubtitle': 'Average in 2024',
    'about.location': 'Location',
    'about.locationValue': 'Pattaya',
    'about.locationSubtitle': 'Tourist hub',
    'about.launch': 'Launch',
    'about.growth': 'Growth',
    'about.now': 'Now',
    'about.cars3': '3 cars',
    'about.cars6': '6 cars',
    'about.cars9': '9 cars',
    'about.growthTitle': 'Company Growth History',
    'about.insurance': 'Insurance',
    'about.insuranceDesc': 'Full Type 1 insurance (ชั้น 1) for vehicles and passengers',
    'about.insuranceCoverage1': 'Full vehicle damage coverage',
    'about.insuranceCoverage2': 'Theft and malicious damage',
    'about.insuranceCoverage3': 'Natural disasters (flood, fire)',
    'about.insuranceCoverage4': 'Medical expenses for driver and passengers',
    'about.insuranceCoverage5': 'Third-party liability',
    'about.insuranceCoverage6': '24/7 roadside assistance and towing',
    'about.transparency': 'Transparency',
    'about.transparencyDesc': 'Monthly reports and real-time metrics access',
    'about.experience': 'Experience',
    'about.experienceDesc': '2+ years of successful rental market operation in Thailand',
    'about.fleetTitle': 'Our Toyota Fleet',
    'about.fleetDesc': 'Premium Toyota vehicles in excellent condition on the scenic roads of Thailand',
    'about.velozDesc': 'Premium 7-seater • Perfect for families',
    'about.yarisDesc': 'Compact sedan • Economical and reliable',

    // === Investment Tiers ===
    'tiers.title': 'Participation Options',
    'tiers.subtitle': 'Choose a partnership loan option',
    'tiers.minInvestment': 'Minimum investment',
    'tiers.fullCost': 'Full vehicle cost',
    'tiers.expectedReturn': 'Expected return (projection)',
    'tiers.after6months': 'After 6 months',
    'tiers.connectWallet': 'Connect Wallet',
    'tiers.allReserved': 'All vehicles reserved',
    'tiers.invest': 'Invest',
    'tiers.perYear': 'per year',
    'tiers.perMonth': '/mo',
    'tiers.upTo': 'up to',
    'tiers.carsLeft': 'cars left',
    'tiers.partnerChoice': 'Partner choice:',
    'tiers.takeReturn': 'Take',
    'tiers.return': 'return',
    'tiers.or': 'OR',
    'tiers.waitCar': 'Wait for',
    'tiers.carOwnership': 'car ownership',
    'tiers.afterLoan': '(after loan repayment)',
    'tiers.withdrawAnytime': 'Withdraw anytime',
    'tiers.feeUntil6mo': 'fee until 6 mo',
    'tiers.fewCarsLeft': 'Few cars left! First come, first served.',
    'tiers.walletInfo': 'Investment wallet (BSC Network):',
    'tiers.acceptedTokens': 'Accepted: USDT, USDC on Binance Smart Chain (BSC)',
    'tiers.networkFee': 'Network fee: ~$0.20',
    // Tier names and descriptions from database
    'tiers.tierName.staking': 'Staking',
    'tiers.tierName.carShare': 'Car Share',
    'tiers.tierDesc.staking': 'Passive income with flexible withdrawal options',
    'tiers.tierDesc.carShare': 'Get car ownership or guaranteed return',
    // Features from database
    'tiers.feature.monthlyRate': '2.5% per month (30% annually)',
    'tiers.feature.withdrawAnytime': 'Withdraw anytime',
    'tiers.feature.earlyFee': '5% fee for withdrawal before 6 months',
    'tiers.feature.monthlyAccrual': 'Monthly interest accrual',
    'tiers.feature.sixMonthChoice': 'After 6 mo: +20% return OR wait for car',
    'tiers.feature.carOwnership': 'Car ownership after loan repayment',
    'tiers.feature.priority': 'Priority: first come, first served',
    'tiers.feature.changeChoice': 'Can change choice before loan closure',

    // === Invest Modal ===
    'modal.title': 'Investment',
    'modal.step': 'Step',
    'modal.of': 'of',
    'modal.agreement': 'Partnership Loan Agreement',
    'modal.scrollToEnd': 'Scroll to the end',
    'modal.agreeTerms': 'I have read and accept the terms',
    'modal.readAgreement': 'Please read the agreement',
    'modal.continue': 'Continue',
    'modal.amount': 'Investment Amount',
    'modal.minAmount': 'Minimum',
    'modal.maxAmount': 'Maximum',
    'modal.expectedReturn': 'Expected return (projection)',
    'modal.expectedReturnCar': 'Expected return up to +20%',
    'modal.payViaWallet': 'Pay via Wallet',
    'modal.confirmInWallet': 'Confirm in your wallet...',
    'modal.paymentDetails': 'Bank Transfer',
    'modal.comingSoon': 'coming soon',
    'modal.awaitingPayment': 'Awaiting payment',
    'modal.awaitingVerification': 'Awaiting verification',
    'modal.back': 'Back',
    'modal.close': 'Close',
    'modal.enterTxHash': 'Enter TX Hash',
    'modal.invalidTxHash': 'Invalid TX Hash format',
    'modal.errorCreating': 'Error creating investment',
    'modal.scrollDown': 'Scroll down',
    'modal.next': 'Next',
    'modal.backToAgreement': '← Back to agreement',
    'modal.choosePayment': 'Choose payment method',
    'modal.testnetMode': '⚠️ TESTNET MODE - BSC Test Network',
    'modal.or': 'or',
    'modal.orCarOwnership': 'or car ownership',
    'modal.applicationCreated': 'Application Created!',
    'modal.investmentPending': 'Investment is under review',
    'modal.amountLabel': 'Amount:',
    'modal.statusLabel': 'Status:',
    'modal.willCheck24h': 'We will verify the transaction within 24 hours',
    'modal.done': 'Done',
    'modal.minError': 'Minimum: ${amount}',
    'modal.maxError': 'For ${amount}+ choose "Car Share"',
    // Agreement text
    'modal.agreementTitle': 'PARTNERSHIP LOAN AGREEMENT',
    'modal.agreementIntro': 'Private loan agreement between individuals under the Thai Civil and Commercial Code.',
    'modal.agreementNature': '1. Transaction Nature:',
    'modal.agreementNatureText': 'Private loan between acquaintances for car rental business development.',
    'modal.agreementNotPublic': 'NOT a public securities offering',
    'modal.agreementRisks': '2. RISKS:',
    'modal.agreementRisksText': 'Returns are',
    'modal.agreementNotGuaranteed': 'PROJECTIONS, NOT GUARANTEED',
    'modal.agreementRisksNote': 'The company owns real assets and has insurance coverage, which minimizes risks.',
    'modal.agreementReturn': '3. Early Withdrawal:',
    'modal.agreementReturnText': 'Early withdrawal is possible with compensation deduction.',
    'modal.agreementTaxes': '4. Taxes:',
    'modal.agreementTaxesText': 'Each party is responsible according to their country\'s laws.',
    'modal.agreementDisputes': '5. Disputes:',
    'modal.agreementDisputesText': 'Resolved under Thai law.',
    'modal.agreementAge': '6. Age:',
    'modal.agreementAgeText': 'Participant confirms being at least',
    'modal.agreementAgeYears': '20 years old',
    'modal.agreementData': '7. Data:',
    'modal.agreementDataText': 'Consent to data processing under Thailand PDPA.',
    'modal.agreementRoadmap': '8. Roadmap:',
    'modal.agreementRoadmapText': 'The development plan is indicative. Timelines and milestones may be adjusted based on market conditions and business opportunities.',
    'modal.agreementVersion': 'Version 1.1 • 08.12.2025 • Thailand My Car, Pattaya',

    // === Investor Dashboard ===
    'dashboard.title': 'Investor Dashboard',
    'dashboard.totalInvested': 'Total Invested',
    'dashboard.totalEarned': 'Total Earned',
    'dashboard.activeInvestments': 'Active Investments',
    'dashboard.pendingPayouts': 'Pending Payouts',
    'dashboard.yourInvestments': 'Your Investments',
    'dashboard.noInvestments': 'You have no investments yet',
    'dashboard.startInvesting': 'Start investing to see your statistics',
    'dashboard.carShare': 'Car Share',
    'dashboard.staking': 'Staking',
    'dashboard.invested': 'Invested',
    'dashboard.earned': 'Earned',
    'dashboard.status': 'Status',
    'dashboard.withdraw': 'Withdraw',
    'dashboard.withdrawalRequest': 'Withdrawal Request',
    'dashboard.withdrawalType': 'Withdrawal Type',
    'dashboard.earningsOnly': 'Earnings only',
    'dashboard.principalOnly': 'Principal only',
    'dashboard.withdrawAll': 'All (principal + earnings)',
    'dashboard.walletAddress': 'BEP20 Wallet Address',
    'dashboard.enterWallet': 'Enter wallet address',
    'dashboard.invalidWallet': 'Invalid address format. BEP20 address must start with 0x and contain 42 characters',
    'dashboard.submitRequest': 'Submit Request',
    'dashboard.cancel': 'Cancel',
    'dashboard.noConnection': 'No server connection. Please check your internet.',
    'dashboard.loadError': 'Error loading data. Please try again later.',
    'dashboard.networkError': 'Network error. Please try again later.',
    'dashboard.myDashboard': 'My Dashboard',
    'dashboard.manageInvestments': 'Manage your investments',
    'dashboard.loading': 'Loading investments...',
    'dashboard.loadingError': 'Loading error',
    'dashboard.retry': 'Retry',
    'dashboard.connectWallet': 'Connect Wallet',
    'dashboard.connectToView': 'Connect your wallet to view investments',
    'dashboard.startInvestingHere': 'Start investing and track your returns here',
    'dashboard.totalBalance': 'Total Balance',
    'dashboard.active': 'Active',
    'dashboard.withdrawn': 'Withdrawn',
    'dashboard.earningsProjection': 'Earnings Projection',
    'dashboard.balanceByMonth': 'Accumulated balance by month',
    'dashboard.balance': 'Balance',
    'dashboard.monthlyIncome': 'Monthly',
    'dashboard.date': 'Date',
    'dashboard.accumulated': 'Accumulated',
    'dashboard.withdrawnPercent': 'Withdrawn %',
    'dashboard.rate': 'Rate',
    'dashboard.locked': 'Locked',
    'dashboard.available': 'Available',
    'dashboard.untilUnlock': 'Until unlock',
    'dashboard.days': 'days',
    'dashboard.months': 'mo.',
    'dashboard.of': 'of',
    'dashboard.availableForWithdraw': 'Available for withdrawal',
    'dashboard.toWithdraw': 'To withdraw',
    'dashboard.statusActive': 'Active',
    'dashboard.statusPending': 'Awaiting payment',
    'dashboard.statusPendingConfirmation': 'Pending confirmation',
    'dashboard.statusWithdrawalRequest': 'Withdrawal request',
    'dashboard.statusCompleted': 'Completed',
    'dashboard.selectWithdrawalType': 'Select withdrawal type',
    'dashboard.walletAddressStep': 'Wallet Address',
    'dashboard.confirmation': 'Confirmation',
    'dashboard.requestSent': 'Request Sent',
    'dashboard.principalStays': 'Principal stays and continues earning',
    'dashboard.earningsStay': 'Earnings stay in account',
    'dashboard.feePercent': '(5% fee)',
    'dashboard.closeInvestment': 'All (close investment)',
    'dashboard.bodyPlusEarnings': 'Principal + earnings',
    'dashboard.earlyWithdrawal': 'Early withdrawal.',
    'dashboard.earlyWithdrawalNote': 'Principal withdrawal before term end incurs 5% fee. Earnings-only withdrawal is fee-free.',
    'dashboard.next': 'Next',
    'dashboard.walletAddressLabel': 'USDT Wallet Address (BEP20 / BSC)',
    'dashboard.important': 'Important!',
    'dashboard.bep20Warning': 'Make sure the address supports BEP20 (BSC) network',
    'dashboard.wrongAddressWarning': 'Sending to wrong address will result in loss of funds',
    'dashboard.checkAddress': 'Double-check the address',
    'dashboard.back': 'Back',
    'dashboard.verify': 'Verify',
    'dashboard.addressForReceiving': 'Address for receiving USDT:',
    'dashboard.confirmAddress': 'I confirm the wallet address is correct and supports BEP20 (BSC) network. I understand that errors will result in loss of funds.',
    'dashboard.totalToWithdraw': 'Total to withdraw:',
    'dashboard.platformFee': 'Platform fee (3%)',
    'dashboard.earlyWithdrawalFee': 'Early withdrawal fee (+5%)',
    'dashboard.youWillReceive': 'You will receive:',
    'dashboard.processingTime': 'Processing time',
    'dashboard.processingUp48h': 'Request processing: up to 48 hours',
    'dashboard.payoutsWeekdays': 'Payouts on weekdays (Mon-Fri)',
    'dashboard.changeAddress': 'Change address',
    'dashboard.sending': 'Sending...',
    'dashboard.sendRequest': 'Send request',
    'dashboard.requestAccepted': 'Request accepted!',
    'dashboard.withdrawalSent': 'Your withdrawal request has been submitted for processing',
    'dashboard.receivingAddress': 'Receiving address:',
    'dashboard.expectTransfer48h': 'Expect transfer within 48 hours.',
    'dashboard.adminMayContact': 'Admin may contact you for confirmation.',
    'dashboard.close': 'Close',
    'dashboard.principal': 'Principal:',
    'dashboard.accumulatedEarnings': 'Accumulated earnings:',
    'dashboard.months_short': 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec',
    'dashboard.months_short_ru': 'Янв|Фев|Мар|Апр|Май|Июн|Июл|Авг|Сен|Окт|Ноя|Дек',

    // === Profile Page ===
    'profile.title': 'Your Profile',
    'profile.yourProfile': 'Your Profile',
    'profile.wallet': 'Wallet',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.save': 'Save',
    'profile.withdrawRequest': 'Withdrawal Request',
    'profile.withdrawSent': 'Withdrawal request sent! An administrator will contact you.',
    'profile.withdrawError': 'Error sending request',
    'profile.status.pending': 'Pending',
    'profile.status.pending_confirmation': 'Under Review',
    'profile.status.active': 'Active',
    'profile.status.withdrawal_requested': 'Withdrawal Requested',
    'profile.status.completed': 'Completed',
    'profile.status.cancelled': 'Cancelled',
    'profile.back': 'Back',
    'profile.memberSince': 'Member since',
    'profile.totalInvested': 'Total Invested',
    'profile.investments': 'Investments',
    'profile.activeInvestments': 'Active',
    'profile.inBaht': 'In Baht',
    'profile.personalInfo': 'Personal Information',
    'profile.namePlaceholder': 'Enter your name',
    'profile.bio': 'About',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.saving': 'Saving...',
    'profile.saveProfile': 'Save Profile',
    'profile.updateSuccess': 'Profile updated successfully!',
    'profile.withdrawalSent': 'Withdrawal request sent! An administrator will contact you.',
    'profile.withdrawalError': 'Error sending request',
    'profile.connectWallet': 'Connect Your Wallet',
    'profile.connectWalletDesc': 'Please connect your wallet to view your profile',
    'profile.statusPending': 'Pending',
    'profile.statusPendingConfirm': 'Under Review',
    'profile.statusActive': 'Active',
    'profile.statusWithdrawalRequested': 'Withdrawal Requested',
    'profile.statusCompleted': 'Completed',
    'profile.statusCancelled': 'Cancelled',
    'profile.sessionExpiredTitle': '⏱️ Session Expired',
    'profile.sessionExpiredDesc': 'Your session has expired. Please reconnect your wallet:',
    'profile.sessionExpiredStep1': 'Click on the wallet button in the top right corner',
    'profile.sessionExpiredStep2': 'Disconnect your current wallet',
    'profile.sessionExpiredStep3': 'Reconnect your wallet',
    'profile.walletNotConnectedTitle': '🔗 Wallet Not Connected',
    'profile.walletNotConnectedDesc': 'To view your profile, you need to connect your wallet. Click the "Connect Wallet" button in the top right corner.',
    'profile.loadFailedTitle': '❌ Loading Error',
    'profile.loadFailedDesc': 'Failed to load profile data. Try refreshing the page or reconnecting your wallet.',

    // === Roadmap ===
    'roadmap.title': 'Roadmap',
    'roadmap.subtitle': 'Project Development Plan',
    'roadmap.q4_2025': 'Q4 2025',
    'roadmap.launch': 'Platform Launch',
    'roadmap.launchItems': 'Web3 platform development|MetaMask integration|Design and UI/UX',
    'roadmap.dec_jan': 'December 2025 - January 2026',
    'roadmap.fundraising': 'Fundraising',
    'roadmap.fundraisingItems': 'Investor acquisition|Reaching ฿2.8M goal|KYC and AML procedures',
    'roadmap.jan_2026': 'January 2026',
    'roadmap.roundClose': 'Round Closing',
    'roadmap.roundCloseItems': 'Fundraising completion|Legal documentation start',
    'roadmap.feb_2026': 'February 2026',
    'roadmap.legal': 'Legal Framework',
    'roadmap.legalItems': 'Share registration|Contract signing|Automated payouts setup',
    'roadmap.mar_2026': 'March 2026',
    'roadmap.firstPayouts': 'First Payouts',
    'roadmap.firstPayoutsItems': 'Monthly payments begin|Real-time dashboard|Governance voting',
    'roadmap.jul_2026': 'July 2026',
    'roadmap.expansion': 'Fleet Expansion',
    'roadmap.expansionItems': 'Expand to 15 vehicles|Thai bank financing|Operations scaling',
    'roadmap.oct_2026': 'October 2026',
    'roadmap.newProducts': 'New Products',
    'roadmap.newProductsItems': 'Leasing at 20% APY launch|Phuket branch opening|Geographic expansion',
    'roadmap.2027': '2027',
    'roadmap.continued': 'To be continued...',
    'roadmap.continuedItems': 'Further development|New directions|International expansion',
    'roadmap.disclaimer': 'This roadmap is indicative. Timelines and milestones may be adjusted based on market conditions, regulatory requirements, and business opportunities. The company reserves the right to make changes to achieve optimal results.',

    // === Footer ===
    'footer.rights': 'All rights reserved',
    'footer.email': 'Email',
    'footer.youtube': 'YouTube',
    'footer.telegram': 'Telegram',
    'footer.contacts': 'Contacts',
    'footer.description': 'Blockchain-powered investment in car rental business',
    'footer.disclaimer': 'Private loans carry risks. Returns are not guaranteed. This is not a public securities offering. The platform is intended for private agreements between acquainted parties.',

    // === Chat Widget ===
    'chat.title': 'Support',
    'chat.placeholder': 'Type a message...',
    'chat.send': 'Send',
    'chat.greeting': 'Hello! How can I help you?',
    'chat.agentName': 'Mira',
    'chat.typing': 'Typing...',
    'chat.consultantOnline': 'Consultant • Online 24/7',
    'chat.endChatConfirm': 'End chat? History will be deleted.',
    'chat.endChat': 'End chat',
    'chat.end': 'End',
    'chat.startChat': 'Start Chat',
    'chat.introduceYourself': 'Introduce yourself so we can help you better',
    'chat.yourName': 'Your name',
    'chat.namePlaceholder': 'What should we call you?',
    'chat.emailOptional': 'Email (optional)',
    'chat.contactManager': 'Contact Manager',
    'chat.waitingForManager': '⏳ Waiting for manager...',
    'chat.writeToManager': 'Write to manager...',
    'chat.writeMessage': 'Type a message...',
    'chat.managerRequestSent': '🎧 Request sent! A manager will join the chat shortly. Please wait...',
    'chat.welcomeMessage': 'Hello, {name}! 👋\n\nI\'m Mira, your Thailand My Car assistant.\n\nI\'m happy to answer your questions about investments, returns, crypto payments, and our fleet!\n\nIf you want to contact a manager - click the 🎧 button below.\n\nHow can I help? 😊',

    // === Common ===
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'or',
    'common.and': 'and',

    // === Months ===
    'month.jan': 'Jan',
    'month.feb': 'Feb',
    'month.mar': 'Mar',
    'month.apr': 'Apr',
    'month.may': 'May',
    'month.jun': 'Jun',
    'month.jul': 'Jul',
    'month.aug': 'Aug',
    'month.sep': 'Sep',
    'month.oct': 'Oct',
    'month.nov': 'Nov',
    'month.dec': 'Dec',

    // === Alerts ===
    'alert.connectWallet': 'Please connect your wallet to invest',

    // === Cookies ===
    'cookies.message': 'We use cookies to operate the site and save your preferences.',
    'cookies.accept': 'Accept',
    'cookies.decline': 'Decline',

    // === Mobile Wallet Helper ===
    'mobileHelper.title': 'Connect from Phone',
    'mobileHelper.subtitle': 'Choose connection method',
    'mobileHelper.recommend': 'Recommended: open in wallet browser',
    'mobileHelper.copyLink': 'Copy link and open in wallet browser:',
    'mobileHelper.noWallet': 'No crypto wallet? Sign in with Email:',
    'mobileHelper.loginEmail': 'Sign in with Email / Google',
    'mobileHelper.tryWalletConnect': 'Try WalletConnect',
    'mobileHelper.walletConnectNote': 'WalletConnect may be slow on some devices',
    'mobileHelper.or': 'or',
  },

  th: {
    // === Navigation ===
    'nav.home': 'หน้าหลัก',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.invest': 'ลงทุน',
    'nav.dashboard': 'แดชบอร์ด',
    'nav.roadmap': 'แผนงาน',
    'nav.profile': 'โปรไฟล์',

    // === Header ===
    'header.slogan': 'ลงทุนในธุรกิจเช่ารถ',
    'header.connect': 'เชื่อมต่อ',
    'header.signing': 'กำลังลงชื่อ...',
    'header.disconnect': 'ยกเลิกการเชื่อมต่อ',
    'header.connectWallet': 'เชื่อมต่อกระเป๋าเงิน',
    'header.language': 'ภาษา',

    // === Hero Section ===
    'hero.badge': 'ลงทุนในธุรกิจเช่ารถผ่านบล็อกเชน',
    'hero.title': 'ลงทุน',
    'hero.titleAccent': 'ในธุรกิจเช่ารถ',
    'hero.titleCrypto': 'ด้วยคริปโต',
    'hero.subtitle': 'รถยนต์ Toyota {count} คัน • เริ่มต้น $1,000 • 2.5%/เดือน หรือเป็นเจ้าของรถ',
    'hero.description': 'ร่วมเป็นเจ้าของกองรถ Toyota ในพัทยา รายได้มั่นคงจากการให้เช่าแก่นักท่องเที่ยว',
    'hero.cta': 'ลงทุนเลย',
    'hero.learnMore': 'เรียนรู้เพิ่มเติม',
    'hero.target': 'เป้าหมาย',
    'hero.collected': 'ระดมทุนแล้ว',
    'hero.investors': 'นักลงทุน',
    'hero.daysLeft': 'วันที่เหลือ',
    'hero.carsAvailable': 'รถที่พร้อม',
    'hero.of': 'จาก',
    'hero.progress': 'ความคืบหน้า',
    'hero.staking': 'สเตกกิ้ง',
    'hero.stakingRate': '2.5%/เดือน',
    'hero.bigInvestors': 'นักลงทุนรายใหญ่',
    'hero.bigInvestorsReturn': 'เป็นเจ้าของรถ',
    'hero.fundraising': 'การระดมทุน',
    'hero.goal': 'เป้าหมาย',
    'hero.carOwnership': 'เจ้าของรถ',
    'hero.available': 'พร้อมให้บริการ',
    'hero.minStaking': 'ขั้นต่ำ $1,000',
    'hero.minCar': 'เจ้าของรถ $12,400',

    // === About Project ===
    'about.title': 'เกี่ยวกับโครงการ',
    'about.subtitle': 'ธุรกิจให้เช่ารถ Toyota ในพัทยา พร้อมผลตอบแทนที่พิสูจน์แล้ว',
    'about.cars': 'รถยนต์',
    'about.carsSubtitle': 'Toyota ในกองรถ',
    'about.monthlyIncome': 'รายได้รายเดือน',
    'about.monthlyIncomeSubtitle': '฿ กระแสเงินสดมั่นคง',
    'about.occupancy': 'อัตราการเช่า',
    'about.occupancySubtitle': 'เฉลี่ยปี 2024',
    'about.location': 'ที่ตั้ง',
    'about.locationValue': 'พัทยา',
    'about.locationSubtitle': 'ศูนย์กลางท่องเที่ยว',
    'about.launch': 'เปิดตัว',
    'about.growth': 'เติบโต',
    'about.now': 'ปัจจุบัน',
    'about.cars3': '3 คัน',
    'about.cars6': '6 คัน',
    'about.cars9': '9 คัน',
    'about.growthTitle': 'ประวัติการเติบโตของบริษัท',
    'about.insurance': 'ประกันภัย',
    'about.insuranceDesc': 'ประกันภัยชั้น 1 ครอบคลุมรถยนต์และผู้โดยสาร',
    'about.insuranceCoverage1': 'คุ้มครองความเสียหายของรถยนต์เต็มที่',
    'about.insuranceCoverage2': 'การโจรกรรมและการกระทำโดยมิชอบ',
    'about.insuranceCoverage3': 'ภัยธรรมชาติ (น้ำท่วม ไฟไหม้)',
    'about.insuranceCoverage4': 'ค่ารักษาพยาบาลผู้ขับขี่และผู้โดยสาร',
    'about.insuranceCoverage5': 'ความรับผิดต่อบุคคลภายนอก',
    'about.insuranceCoverage6': 'บริการช่วยเหลือฉุกเฉินและลากรถ 24/7',
    'about.transparency': 'ความโปร่งใส',
    'about.transparencyDesc': 'รายงานรายเดือนและเข้าถึงข้อมูลแบบเรียลไทม์',
    'about.experience': 'ประสบการณ์',
    'about.experienceDesc': 'ดำเนินธุรกิจให้เช่ารถในไทยมากกว่า 2 ปี',
    'about.fleetTitle': 'กองรถ Toyota ของเรา',
    'about.fleetDesc': 'รถยนต์ Toyota คุณภาพพรีเมียมในสภาพดีเยี่ยม บนถนนที่สวยงามของประเทศไทย',
    'about.velozDesc': 'MPV 7 ที่นั่งพรีเมียม • เหมาะสำหรับครอบครัว',
    'about.yarisDesc': 'รถซีดานขนาดกะทัดรัด • ประหยัดและเชื่อถือได้',

    // === Investment Tiers ===
    'tiers.title': 'แผนการลงทุน',
    'tiers.subtitle': 'เลือกแผนที่เหมาะกับท่าน',
    'tiers.minInvestment': 'ขั้นต่ำ',
    'tiers.fullCost': 'ราคาเต็มรถยนต์',
    'tiers.expectedReturn': 'ผลตอบแทนที่คาดหวัง (ประมาณการ)',
    'tiers.after6months': 'หลังจาก 6 เดือน',
    'tiers.connectWallet': 'เชื่อมต่อกระเป๋าเงิน',
    'tiers.allReserved': 'รถทั้งหมดถูกจองแล้ว',
    'tiers.invest': 'ลงทุน',
    'tiers.perYear': 'ต่อปี',
    'tiers.perMonth': '/เดือน',
    'tiers.upTo': 'สูงสุด',
    'tiers.carsLeft': 'คันที่เหลือ',
    'tiers.partnerChoice': 'ทางเลือกสำหรับพาร์ทเนอร์:',
    'tiers.takeReturn': 'รับ',
    'tiers.return': 'ผลตอบแทน',
    'tiers.or': 'หรือ',
    'tiers.waitCar': 'รอ',
    'tiers.carOwnership': 'เป็นเจ้าของรถ',
    'tiers.afterLoan': '(หลังชำระสินเชื่อ)',
    'tiers.withdrawAnytime': 'ถอนได้ทุกเมื่อ',
    'tiers.feeUntil6mo': 'ค่าธรรมเนียมก่อน 6 เดือน',
    'tiers.fewCarsLeft': 'เหลือรถน้อย! ใครมาก่อนได้ก่อน',
    'tiers.walletInfo': 'กระเป๋าเงินสำหรับลงทุน (BSC Network):',
    'tiers.acceptedTokens': 'รับ: USDT, USDC บน Binance Smart Chain (BSC)',
    'tiers.networkFee': 'ค่าธรรมเนียมเครือข่าย: ~$0.20',
    // Tier names and descriptions
    'tiers.tierName.staking': 'สเตกกิ้ง',
    'tiers.tierName.carShare': 'ส่วนแบ่งในรถยนต์',
    'tiers.tierDesc.staking': 'รายได้แบบ passive พร้อมเงื่อนไขการถอนที่ยืดหยุ่น',
    'tiers.tierDesc.carShare': 'เป็นเจ้าของรถหรือรับผลตอบแทนที่รับประกัน',
    // Features
    'tiers.feature.monthlyRate': '2.5% ต่อเดือน (30% ต่อปี)',
    'tiers.feature.withdrawAnytime': 'ถอนได้ทุกเมื่อ',
    'tiers.feature.earlyFee': 'ค่าธรรมเนียม 5% สำหรับการถอนก่อน 6 เดือน',
    'tiers.feature.monthlyAccrual': 'ดอกเบี้ยสะสมรายเดือน',
    'tiers.feature.sixMonthChoice': 'หลัง 6 เดือน: +20% ผลตอบแทน หรือ รอรับรถ',
    'tiers.feature.carOwnership': 'เป็นเจ้าของรถหลังชำระสินเชื่อ',
    'tiers.feature.priority': 'ลำดับความสำคัญ: ใครมาก่อนได้ก่อน',
    'tiers.feature.changeChoice': 'เปลี่ยนใจได้ก่อนปิดสินเชื่อ',

    // === Dashboard ===
    'dashboard.title': 'แดชบอร์ดนักลงทุน',
    'dashboard.totalInvested': 'ลงทุนทั้งหมด',
    'dashboard.totalEarned': 'รายได้ทั้งหมด',
    'dashboard.activeInvestments': 'การลงทุนที่ใช้งาน',
    'dashboard.pendingPayouts': 'รอจ่าย',
    'dashboard.yourInvestments': 'การลงทุนของท่าน',
    'dashboard.noInvestments': 'ยังไม่มีการลงทุน',
    'dashboard.startInvesting': 'เริ่มลงทุน',
    'dashboard.startInvestingHere': 'เริ่มลงทุนและติดตามผลตอบแทนที่นี่',
    'dashboard.carShare': 'ส่วนแบ่งในรถ',
    'dashboard.staking': 'สเตกกิ้ง',
    'dashboard.invested': 'ลงทุนแล้ว',
    'dashboard.earned': 'รายได้',
    'dashboard.date': 'วันที่',
    'dashboard.accumulated': 'สะสม',
    'dashboard.withdrawnPercent': 'ถอนแล้ว %',
    'dashboard.rate': 'อัตรา',
    'dashboard.status': 'สถานะ',
    'dashboard.locked': 'ล็อค',
    'dashboard.available': 'พร้อมใช้',
    'dashboard.untilUnlock': 'จนกว่าจะปลดล็อค',
    'dashboard.toWithdraw': 'พร้อมถอน',
    'dashboard.withdraw': 'ถอน',
    'dashboard.days': 'วัน',
    'dashboard.months': 'เดือน',
    'dashboard.of': 'จาก',
    'dashboard.balance': 'ยอดคงเหลือ',
    'dashboard.monthlyIncome': 'รายได้/เดือน',
    'dashboard.myDashboard': 'แดชบอร์ดของฉัน',
    'dashboard.manageInvestments': 'จัดการการลงทุนของท่าน',
    'dashboard.loading': 'กำลังโหลด...',
    'dashboard.loadingError': 'เกิดข้อผิดพลาดในการโหลด',
    'dashboard.loadError': 'เกิดข้อผิดพลาดในการโหลดข้อมูล กรุณาลองใหม่',
    'dashboard.retry': 'ลองอีกครั้ง',
    'dashboard.connectWallet': 'เชื่อมต่อกระเป๋าเงิน',
    'dashboard.connectToView': 'เชื่อมต่อกระเป๋าเงินเพื่อดูการลงทุน',
    'dashboard.totalBalance': 'ยอดคงเหลือรวม',
    'dashboard.active': 'ใช้งาน',
    'dashboard.withdrawn': 'ถอนแล้ว',
    'dashboard.earningsProjection': 'ประมาณการรายได้',
    'dashboard.balanceByMonth': 'ยอดคงเหลือสะสมรายเดือน',
    'dashboard.noConnection': 'ไม่มีการเชื่อมต่อเซิร์ฟเวอร์',
    'dashboard.networkError': 'เกิดข้อผิดพลาดเครือข่าย',
    'dashboard.selectWithdrawalType': 'เลือกประเภทการถอน',
    'dashboard.walletAddressStep': 'ที่อยู่กระเป๋าเงิน',
    'dashboard.confirmation': 'ยืนยัน',
    'dashboard.requestSent': 'ส่งคำขอแล้ว',
    'dashboard.earningsOnly': 'เฉพาะดอกเบี้ย',
    'dashboard.principalOnly': 'เงินต้นเท่านั้น',
    'dashboard.withdrawAll': 'ทั้งหมด (เงินต้น + ดอกเบี้ย)',
    'dashboard.principalStays': 'เงินต้นยังคงทำงานต่อ',
    'dashboard.earningsStay': 'ดอกเบี้ยยังคงอยู่ในบัญชี',
    'dashboard.feePercent': '(ค่าธรรมเนียม 5%)',
    'dashboard.closeInvestment': 'ทั้งหมด (ปิดการลงทุน)',
    'dashboard.bodyPlusEarnings': 'เงินต้น + ดอกเบี้ย',
    'dashboard.earlyWithdrawal': 'การถอนก่อนกำหนด',
    'dashboard.earlyWithdrawalNote': 'การถอนเงินต้นก่อนครบกำหนดมีค่าธรรมเนียม 5%',
    'dashboard.next': 'ถัดไป',
    'dashboard.walletAddressLabel': 'ที่อยู่กระเป๋าเงิน USDT (BEP20 / BSC)',
    'dashboard.enterWallet': 'กรอกที่อยู่กระเป๋าเงิน',
    'dashboard.invalidWallet': 'ที่อยู่ไม่ถูกต้อง ต้องเริ่มด้วย 0x และมี 42 ตัวอักษร',
    'dashboard.important': 'สำคัญ!',
    'dashboard.bep20Warning': 'ตรวจสอบว่าที่อยู่รองรับเครือข่าย BEP20 (BSC)',
    'dashboard.wrongAddressWarning': 'การส่งไปที่อยู่ผิดจะทำให้สูญเสียเงิน',
    'dashboard.checkAddress': 'ตรวจสอบที่อยู่อีกครั้ง',
    'dashboard.back': 'กลับ',
    'dashboard.verify': 'ตรวจสอบ',
    'dashboard.addressForReceiving': 'ที่อยู่สำหรับรับ USDT:',
    'dashboard.confirmAddress': 'ข้าพเจ้ายืนยันว่าที่อยู่ถูกต้องและรองรับ BEP20 (BSC)',
    'dashboard.totalToWithdraw': 'ยอดรวมที่จะถอน:',
    'dashboard.platformFee': 'ค่าธรรมเนียมแพลตฟอร์ม (3%)',
    'dashboard.earlyWithdrawalFee': 'ค่าธรรมเนียมถอนก่อนกำหนด (+5%)',
    'dashboard.youWillReceive': 'ท่านจะได้รับ:',
    'dashboard.processingTime': 'เวลาดำเนินการ',
    'dashboard.processingUp48h': 'ดำเนินการ: ไม่เกิน 48 ชั่วโมง',
    'dashboard.payoutsWeekdays': 'จ่ายในวันทำการ (จันทร์-ศุกร์)',
    'dashboard.changeAddress': 'เปลี่ยนที่อยู่',
    'dashboard.sending': 'กำลังส่ง...',
    'dashboard.sendRequest': 'ส่งคำขอ',
    'dashboard.requestAccepted': 'รับคำขอแล้ว!',
    'dashboard.withdrawalSent': 'ส่งคำขอถอนเงินแล้ว',
    'dashboard.receivingAddress': 'ที่อยู่รับ:',
    'dashboard.expectTransfer48h': 'คาดว่าจะโอนภายใน 48 ชั่วโมง',
    'dashboard.adminMayContact': 'ผู้ดูแลอาจติดต่อท่านเพื่อยืนยัน',
    'dashboard.close': 'ปิด',
    'dashboard.cancel': 'ยกเลิก',
    'dashboard.principal': 'เงินต้น:',
    'dashboard.accumulatedEarnings': 'ดอกเบี้ยสะสม:',
    'dashboard.availableForWithdraw': 'พร้อมถอน',
    'dashboard.statusActive': 'ใช้งาน',
    'dashboard.statusPending': 'รอชำระเงิน',
    'dashboard.statusPendingConfirmation': 'รอยืนยัน',
    'dashboard.statusWithdrawalRequest': 'คำขอถอนเงิน',
    'dashboard.statusCompleted': 'เสร็จสิ้น',

    // === Withdrawal Modal ===
    'withdraw.title': 'ถอนเงิน',
    'withdraw.step1': 'ขั้นตอนที่ 1: เลือกประเภท',
    'withdraw.step2': 'ขั้นตอนที่ 2: ระบุที่อยู่กระเป๋าเงิน',
    'withdraw.step3': 'ขั้นตอนที่ 3: ยืนยัน',
    'withdraw.step4': 'ขั้นตอนที่ 4: สำเร็จ',
    'withdraw.typeInterest': 'เฉพาะดอกเบี้ย',
    'withdraw.typePrincipal': 'เงินต้น',
    'withdraw.typeAll': 'ทั้งหมด',
    'withdraw.earlyWarning': 'คำเตือน: การถอนก่อนกำหนดอาจมีค่าธรรมเนียม',
    'withdraw.walletAddress': 'ที่อยู่กระเป๋าเงิน',
    'withdraw.walletPlaceholder': 'กรอกที่อยู่กระเป๋าเงิน USDT (BEP-20)',
    'withdraw.amount': 'จำนวน',
    'withdraw.fee': 'ค่าธรรมเนียม',
    'withdraw.youReceive': 'ท่านจะได้รับ',
    'withdraw.confirm': 'ยืนยันการถอน',
    'withdraw.success': 'ถอนเงินสำเร็จ!',
    'withdraw.successDesc': 'เงินจะโอนเข้ากระเป๋าเงินของท่านภายใน 24 ชั่วโมง',
    'withdraw.back': 'กลับ',
    'withdraw.next': 'ถัดไป',
    'withdraw.close': 'ปิด',

    // === Profile ===
    'profile.title': 'โปรไฟล์',
    'profile.yourProfile': 'โปรไฟล์ของท่าน',
    'profile.walletAddress': 'ที่อยู่กระเป๋าเงิน',
    'profile.memberSince': 'สมาชิกตั้งแต่',
    'profile.totalInvested': 'ลงทุนทั้งหมด',
    'profile.totalEarned': 'รายได้ทั้งหมด',
    'profile.investments': 'การลงทุน',
    'profile.activeInvestments': 'ใช้งาน',
    'profile.inBaht': 'เป็นเงินบาท',
    'profile.personalInfo': 'ข้อมูลส่วนบุคคล',
    'profile.name': 'ชื่อ',
    'profile.namePlaceholder': 'กรอกชื่อของท่าน',
    'profile.bio': 'เกี่ยวกับ',
    'profile.bioPlaceholder': 'บอกเราเกี่ยวกับตัวท่าน...',
    'profile.saving': 'กำลังบันทึก...',
    'profile.saveProfile': 'บันทึกโปรไฟล์',
    'profile.updateSuccess': 'อัปเดตโปรไฟล์สำเร็จ!',
    'profile.withdrawalSent': 'ส่งคำขอถอนเงินแล้ว! ผู้ดูแลจะติดต่อท่าน',
    'profile.withdrawalError': 'เกิดข้อผิดพลาดในการส่งคำขอ',
    'profile.connectWallet': 'เชื่อมต่อกระเป๋าเงิน',
    'profile.connectWalletDesc': 'กรุณาเชื่อมต่อกระเป๋าเงินเพื่อดูโปรไฟล์',
    'profile.back': 'กลับ',
    'profile.statusPending': 'รอดำเนินการ',
    'profile.statusPendingConfirm': 'กำลังตรวจสอบ',
    'profile.statusActive': 'ใช้งาน',
    'profile.statusWithdrawalRequested': 'ร้องขอถอนเงิน',
    'profile.statusCompleted': 'เสร็จสิ้น',
    'profile.statusCancelled': 'ยกเลิก',
    'profile.sessionExpiredTitle': '⏱️ หมดเวลาเซสชัน',
    'profile.sessionExpiredDesc': 'เซสชันของท่านหมดอายุ กรุณาเชื่อมต่อกระเป๋าเงินใหม่:',
    'profile.sessionExpiredStep1': 'คลิกที่ปุ่มกระเป๋าเงินมุมขวาบน',
    'profile.sessionExpiredStep2': 'ยกเลิกการเชื่อมต่อกระเป๋าเงินปัจจุบัน',
    'profile.sessionExpiredStep3': 'เชื่อมต่อกระเป๋าเงินใหม่',
    'profile.walletNotConnectedTitle': '🔗 ยังไม่ได้เชื่อมต่อกระเป๋าเงิน',
    'profile.walletNotConnectedDesc': 'หากต้องการดูโปรไฟล์ กรุณาเชื่อมต่อกระเป๋าเงินโดยคลิกปุ่ม "เชื่อมต่อกระเป๋าเงิน" มุมขวาบน',
    'profile.loadFailedTitle': '❌ เกิดข้อผิดพลาดในการโหลด',
    'profile.loadFailedDesc': 'ไม่สามารถโหลดข้อมูลโปรไฟล์ได้ กรุณารีเฟรชหน้าหรือเชื่อมต่อกระเป๋าเงินใหม่',
    'profile.settings': 'การตั้งค่า',
    'profile.notifications': 'การแจ้งเตือน',
    'profile.language': 'ภาษา',
    'profile.theme': 'ธีม',
    'profile.security': 'ความปลอดภัย',

    // === Invest Modal ===
    'modal.title': 'การลงทุน',
    'modal.step': 'ขั้นตอน',
    'modal.of': 'จาก',
    'modal.agreement': 'สัญญาเงินกู้หุ้นส่วน',
    'modal.scrollToEnd': 'เลื่อนไปที่ท้ายสุด',
    'modal.agreeTerms': 'ข้าพเจ้าได้อ่านและยอมรับเงื่อนไข',
    'modal.readAgreement': 'กรุณาอ่านสัญญา',
    'modal.continue': 'ดำเนินการต่อ',
    'modal.amount': 'จำนวนเงินลงทุน',
    'modal.minAmount': 'ขั้นต่ำ',
    'modal.maxAmount': 'สูงสุด',
    'modal.expectedReturn': 'ผลตอบแทนที่คาดหวัง (ประมาณการ)',
    'modal.expectedReturnCar': 'ผลตอบแทนที่คาดหวังสูงสุด +20%',
    'modal.payViaWallet': 'ชำระผ่านกระเป๋าเงิน',
    'modal.confirmInWallet': 'ยืนยันในกระเป๋าเงิน...',
    'modal.paymentDetails': 'โอนเงินผ่านธนาคาร',
    'modal.comingSoon': 'เร็วๆ นี้',
    'modal.awaitingPayment': 'รอการชำระเงิน',
    'modal.awaitingVerification': 'รอการตรวจสอบ',
    'modal.back': 'กลับ',
    'modal.close': 'ปิด',
    'modal.enterTxHash': 'กรอก TX Hash',
    'modal.invalidTxHash': 'รูปแบบ TX Hash ไม่ถูกต้อง',
    'modal.errorCreating': 'เกิดข้อผิดพลาดในการสร้างการลงทุน',
    'modal.scrollDown': 'เลื่อนลง',
    'modal.next': 'ถัดไป',
    'modal.backToAgreement': '← กลับไปที่สัญญา',
    'modal.choosePayment': 'เลือกวิธีการชำระเงิน',
    'modal.testnetMode': '⚠️ โหมดทดสอบ - BSC Test Network',
    'modal.or': 'หรือ',
    'modal.orCarOwnership': 'หรือเป็นเจ้าของรถ',
    'modal.applicationCreated': 'สร้างคำขอแล้ว!',
    'modal.investmentPending': 'การลงทุนอยู่ระหว่างการพิจารณา',
    'modal.amountLabel': 'จำนวน:',
    'modal.statusLabel': 'สถานะ:',
    'modal.willCheck24h': 'เราจะตรวจสอบธุรกรรมภายใน 24 ชั่วโมง',
    'modal.done': 'เสร็จสิ้น',
    'modal.minError': 'ขั้นต่ำ: ${amount}',
    'modal.maxError': 'สำหรับ ${amount}+ กรุณาเลือก "ส่วนแบ่งในรถยนต์"',
    // Agreement text
    'modal.agreementTitle': 'สัญญาเงินกู้หุ้นส่วน',
    'modal.agreementIntro': 'สัญญากู้ยืมเงินส่วนบุคคลระหว่างบุคคลตามประมวลกฎหมายแพ่งและพาณิชย์แห่งประเทศไทย',
    'modal.agreementNature': '1. ลักษณะธุรกรรม:',
    'modal.agreementNatureText': 'เงินกู้ส่วนบุคคลระหว่างคนรู้จักเพื่อพัฒนาธุรกิจให้เช่ารถ',
    'modal.agreementNotPublic': 'ไม่ใช่การเสนอขายหลักทรัพย์ต่อสาธารณะ',
    'modal.agreementRisks': '2. ความเสี่ยง:',
    'modal.agreementRisksText': 'ผลตอบแทนเป็น',
    'modal.agreementNotGuaranteed': 'ประมาณการ ไม่รับประกัน',
    'modal.agreementRisksNote': 'บริษัทเป็นเจ้าของทรัพย์สินจริงและมีความคุ้มครองประกันภัย ซึ่งช่วยลดความเสี่ยง',
    'modal.agreementReturn': '3. การถอนก่อนกำหนด:',
    'modal.agreementReturnText': 'สามารถถอนก่อนกำหนดได้พร้อมหักค่าชดเชย',
    'modal.agreementTaxes': '4. ภาษี:',
    'modal.agreementTaxesText': 'แต่ละฝ่ายรับผิดชอบตามกฎหมายของประเทศตน',
    'modal.agreementDisputes': '5. ข้อพิพาท:',
    'modal.agreementDisputesText': 'แก้ไขตามกฎหมายไทย',
    'modal.agreementAge': '6. อายุ:',
    'modal.agreementAgeText': 'ผู้เข้าร่วมยืนยันว่ามีอายุอย่างน้อย',
    'modal.agreementAgeYears': '20 ปี',
    'modal.agreementData': '7. ข้อมูล:',
    'modal.agreementDataText': 'ยินยอมให้ประมวลผลข้อมูลตาม PDPA ประเทศไทย',
    'modal.agreementRoadmap': '8. แผนงาน:',
    'modal.agreementRoadmapText': 'แผนพัฒนาเป็นเพียงการประมาณ ระยะเวลาและเหตุการณ์สำคัญอาจปรับเปลี่ยนตามสภาพตลาดและโอกาสทางธุรกิจ',
    'modal.agreementVersion': 'เวอร์ชัน 1.1 • 08.12.2025 • Thailand My Car, พัทยา',

    // === Months ===
    'month.jan': 'ม.ค.',
    'month.feb': 'ก.พ.',
    'month.mar': 'มี.ค.',
    'month.apr': 'เม.ย.',
    'month.may': 'พ.ค.',
    'month.jun': 'มิ.ย.',
    'month.jul': 'ก.ค.',
    'month.aug': 'ส.ค.',
    'month.sep': 'ก.ย.',
    'month.oct': 'ต.ค.',
    'month.nov': 'พ.ย.',
    'month.dec': 'ธ.ค.',

    // === Roadmap ===
    'roadmap.title': 'แผนงาน',
    'roadmap.subtitle': 'แผนพัฒนาโครงการ',
    'roadmap.q4_2025': 'ไตรมาส 4 ปี 2025',
    'roadmap.launch': 'เปิดตัวแพลตฟอร์ม',
    'roadmap.launchItems': 'พัฒนาแพลตฟอร์ม Web3|เชื่อมต่อ MetaMask|ออกแบบ UI/UX',
    'roadmap.dec_jan': 'ธันวาคม 2025 - มกราคม 2026',
    'roadmap.fundraising': 'ระดมทุน',
    'roadmap.fundraisingItems': 'ดึงดูดนักลงทุน|บรรลุเป้าหมาย ฿2.8M|ขั้นตอน KYC และ AML',
    'roadmap.jan_2026': 'มกราคม 2026',
    'roadmap.roundClose': 'ปิดรอบระดมทุน',
    'roadmap.roundCloseItems': 'สิ้นสุดการระดมทุน|เริ่มดำเนินการทางกฎหมาย',
    'roadmap.feb_2026': 'กุมภาพันธ์ 2026',
    'roadmap.legal': 'กระบวนการทางกฎหมาย',
    'roadmap.legalItems': 'จดทะเบียนหุ้น|ลงนามสัญญา|ตั้งค่าการจ่ายเงินอัตโนมัติ',
    'roadmap.mar_2026': 'มีนาคม 2026',
    'roadmap.firstPayouts': 'การจ่ายเงินครั้งแรก',
    'roadmap.firstPayoutsItems': 'เริ่มจ่ายเงินรายเดือน|แดชบอร์ดข้อมูลจริง|การลงคะแนน Governance',
    'roadmap.jul_2026': 'กรกฎาคม 2026',
    'roadmap.expansion': 'ขยายกองรถ',
    'roadmap.expansionItems': 'ขยายเป็น 15 คัน|สินเชื่อธนาคารในไทย|ขยายการดำเนินงาน',
    'roadmap.oct_2026': 'ตุลาคม 2026',
    'roadmap.newProducts': 'ผลิตภัณฑ์ใหม่',
    'roadmap.newProductsItems': 'เปิดตัวลีสซิ่ง 20% ต่อปี|เปิดสาขาภูเก็ต|ขยายพื้นที่ธุรกิจ',
    'roadmap.2027': '2027',
    'roadmap.continued': 'ยังมีต่อ...',
    'roadmap.continuedItems': 'การพัฒนาต่อเนื่อง|ทิศทางใหม่|ขยายสู่ต่างประเทศ',
    'roadmap.disclaimer': 'แผนงานนี้เป็นเพียงแนวทาง กำหนดเวลาและขั้นตอนอาจปรับเปลี่ยนตามสภาพตลาด ข้อกำหนดด้านกฎระเบียบ และโอกาสทางธุรกิจ บริษัทสงวนสิทธิ์ในการเปลี่ยนแปลงเพื่อผลลัพธ์ที่ดีที่สุด',

    // === Footer ===
    'footer.description': 'แพลตฟอร์มลงทุนในธุรกิจเช่ารถในประเทศไทย',
    'footer.quickLinks': 'ลิงก์ด่วน',
    'footer.legal': 'กฎหมาย',
    'footer.terms': 'ข้อกำหนดการใช้งาน',
    'footer.privacy': 'นโยบายความเป็นส่วนตัว',
    'footer.contact': 'ติดต่อเรา',
    'footer.contacts': 'ติดต่อ',
    'footer.email': 'อีเมล',
    'footer.youtube': 'YouTube',
    'footer.telegram': 'Telegram',
    'footer.rights': 'สงวนลิขสิทธิ์',
    'footer.disclaimer': 'การลงทุนมีความเสี่ยง โปรดศึกษาข้อมูลก่อนตัดสินใจลงทุน',

    // === Common ===
    'common.loading': 'กำลังโหลด...',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.cancel': 'ยกเลิก',
    'common.confirm': 'ยืนยัน',
    'common.save': 'บันทึก',
    'common.edit': 'แก้ไข',
    'common.delete': 'ลบ',
    'common.close': 'ปิด',
    'common.back': 'กลับ',
    'common.next': 'ถัดไป',
    'common.submit': 'ส่ง',
    'common.search': 'ค้นหา',
    'common.filter': 'กรอง',
    'common.sort': 'เรียงลำดับ',
    'common.all': 'ทั้งหมด',
    'common.none': 'ไม่มี',
    'common.yes': 'ใช่',
    'common.no': 'ไม่',
    'common.or': 'หรือ',
    'common.and': 'และ',

    // === Chat ===
    'chat.title': 'แชทกับเรา',
    'chat.placeholder': 'พิมพ์ข้อความ...',
    'chat.send': 'ส่ง',
    'chat.agentName': 'มิระ',
    'chat.typing': 'กำลังพิมพ์...',
    'chat.consultantOnline': 'ที่ปรึกษาออนไลน์',
    'chat.startChat': 'เริ่มแชท',
    'chat.introduceYourself': 'กรุณาแนะนำตัวท่าน',
    'chat.yourName': 'ชื่อของท่าน',
    'chat.namePlaceholder': 'กรอกชื่อของท่าน',
    'chat.emailOptional': 'อีเมล (ไม่บังคับ)',
    'chat.welcomeMessage': 'สวัสดีค่ะ {name}! ยินดีต้อนรับสู่ Thailand My Car ดิฉันชื่อมิระ มีอะไรให้ช่วยคะ?',
    'chat.contactManager': 'ติดต่อผู้จัดการ',
    'chat.managerRequestSent': 'ส่งคำขอติดต่อผู้จัดการแล้ว กรุณารอสักครู่ค่ะ',
    'chat.waitingForManager': 'กำลังรอผู้จัดการ...',
    'chat.writeMessage': 'เขียนข้อความ...',
    'chat.writeToManager': 'เขียนถึงผู้จัดการ...',
    'chat.endChat': 'จบแชท',
    'chat.endChatConfirm': 'ท่านแน่ใจหรือไม่ว่าต้องการจบแชท?',
    'chat.end': 'จบ',

    // === Support Modal ===
    'support.title': 'ศูนย์ช่วยเหลือ',
    'support.faq': 'คำถามที่พบบ่อย',
    'support.contact': 'ติดต่อเรา',
    'support.telegram': 'Telegram',
    'support.email': 'อีเมล',
    'support.phone': 'โทรศัพท์',

    // === Alerts ===
    'alert.connectWallet': 'กรุณาเชื่อมต่อกระเป๋าเงินเพื่อลงทุน',

    // === Cookies ===
    'cookies.message': 'เราใช้คุกกี้เพื่อการทำงานของเว็บไซต์และบันทึกการตั้งค่าของท่าน',
    'cookies.accept': 'ยอมรับ',
    'cookies.decline': 'ปฏิเสธ',

    // === Mobile Wallet Helper ===
    'mobileHelper.title': 'เชื่อมต่อจากโทรศัพท์',
    'mobileHelper.subtitle': 'เลือกวิธีการเชื่อมต่อ',
    'mobileHelper.recommend': 'แนะนำ: เปิดในเบราว์เซอร์กระเป๋าเงิน',
    'mobileHelper.copyLink': 'คัดลอกลิงก์และเปิดในเบราว์เซอร์กระเป๋าเงิน:',
    'mobileHelper.noWallet': 'ไม่มีกระเป๋าเงินคริปโต? เข้าสู่ระบบด้วยอีเมล:',
    'mobileHelper.loginEmail': 'เข้าสู่ระบบด้วยอีเมล / Google',
    'mobileHelper.tryWalletConnect': 'ลอง WalletConnect',
    'mobileHelper.walletConnectNote': 'WalletConnect อาจช้าในบางอุปกรณ์',
    'mobileHelper.or': 'หรือ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
  initialLanguage?: Language;
}

export function LanguageProvider({ children, initialLanguage }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (initialLanguage) return initialLanguage;
    const saved = localStorage.getItem('thailand-my-car-lang');
    return (saved === 'en' || saved === 'ru' || saved === 'th') ? saved as Language : 'ru';
  });

  useEffect(() => {
    localStorage.setItem('thailand-my-car-lang', language);
    // Update HTML lang attribute
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  /**
   * Translation function with optional parameter interpolation
   * @param key - Translation key (e.g., 'hero.title')
   * @param params - Optional parameters for interpolation (e.g., { count: 5 })
   * @returns Translated string
   */
  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || translations['ru'][key] || key;

    // Interpolate parameters if provided
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(new RegExp(`{${paramKey}}`, 'g'), String(value));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// Helper function to get month name
export function getMonthName(monthIndex: number, t: (key: string) => string): string {
  const months = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];
  return t(`month.${months[monthIndex]}`);
}
